export const gearBuildTags = [
  'ballistics', 'penetration', 'armor-break', 'precision', 'projectile', 'recoil',
  'mobility', 'low-g', 'thermal', 'heat', 'venting', 'capacitor', 'cooldown',
  'systems', 'disruption', 'relay', 'mark', 'pressure', 'vacuum', 'defense',
] as const;

export type GearBuildTag = (typeof gearBuildTags)[number];
export type GearStatScope = 'local-base' | 'local-affix' | 'global' | 'skill-family' | 'environment';
export type GearStatValueKind = 'flat' | 'percent' | 'multiplier' | 'boolean' | 'rule';
export type GearClassAffinity = 'vanguard' | 'vector' | 'systems';

type GearStatSeed = {
  id: string;
  label: string;
  scope: GearStatScope;
  valueKind: GearStatValueKind;
  tags: readonly GearBuildTag[];
  description: string;
};

export const gearStatDefinitions = [
  { id: 'local.recoil-absorption', label: 'Recoil absorption', scope: 'local-base', valueKind: 'percent', tags: ['recoil', 'precision', 'defense'], description: 'Reduces recoil generated by this equipment frame.' },
  { id: 'local.projectile-velocity-penalty', label: 'Projectile velocity penalty', scope: 'local-base', valueKind: 'percent', tags: ['projectile', 'precision'], description: 'Reduces projectile velocity produced by this equipment frame.' },
  { id: 'local.projectile-velocity', label: 'Projectile velocity', scope: 'local-base', valueKind: 'percent', tags: ['ballistics', 'precision', 'projectile'], description: 'Raises projectile velocity produced by this equipment frame.' },
  { id: 'local.penetration', label: 'Penetration', scope: 'local-base', valueKind: 'flat', tags: ['penetration', 'armor-break', 'precision'], description: 'Adds penetration to attacks produced by this equipment frame.' },
  { id: 'local.penetration-penalty', label: 'Penetration penalty', scope: 'local-base', valueKind: 'flat', tags: ['penetration', 'armor-break'], description: 'Reduces penetration produced by this equipment frame.' },
  { id: 'local.heat-per-shot-penalty', label: 'Heat per shot penalty', scope: 'local-base', valueKind: 'percent', tags: ['thermal', 'heat'], description: 'Raises heat generated by each shot from this equipment frame.' },
  { id: 'local.magazine-capacity', label: 'Magazine capacity', scope: 'local-base', valueKind: 'flat', tags: ['ballistics', 'systems'], description: 'Adds magazine capacity to this weapon frame.' },
  { id: 'local.reload-time-penalty', label: 'Reload time penalty', scope: 'local-base', valueKind: 'percent', tags: ['ballistics', 'systems'], description: 'Increases reload time for this weapon frame.' },
  { id: 'local.knockback', label: 'Knockback', scope: 'local-base', valueKind: 'multiplier', tags: ['ballistics', 'recoil', 'mobility'], description: 'Raises physical shove delivered by this weapon frame.' },
  { id: 'local.recoil-impulse-penalty', label: 'Recoil impulse penalty', scope: 'local-base', valueKind: 'percent', tags: ['recoil', 'mobility'], description: 'Raises discharge impulse generated by this weapon frame.' },
  { id: 'local.direct-output', label: 'Direct output', scope: 'local-base', valueKind: 'percent', tags: ['ballistics', 'armor-break'], description: 'Raises direct weapon output produced by this frame.' },
  { id: 'local.recoil-penalty', label: 'Recoil penalty', scope: 'local-base', valueKind: 'percent', tags: ['recoil'], description: 'Raises recoil generated by this equipment frame.' },
  { id: 'local.heat-dissipation', label: 'Heat dissipation', scope: 'local-base', valueKind: 'percent', tags: ['thermal', 'heat', 'venting'], description: 'Raises heat rejection available to this equipment frame.' },
  { id: 'local.reload-speed', label: 'Reload speed', scope: 'local-base', valueKind: 'percent', tags: ['ballistics', 'systems'], description: 'Raises reload and cycling speed on this equipment frame.' },
  { id: 'local.direct-output-penalty', label: 'Direct output penalty', scope: 'local-base', valueKind: 'percent', tags: ['ballistics'], description: 'Reduces direct weapon output produced by this frame.' },
  { id: 'local.armor-reserve', label: 'Armor reserve', scope: 'local-base', valueKind: 'flat', tags: ['defense', 'pressure'], description: 'Adds armor reserve supplied by this equipment frame.' },
  { id: 'local.armor-reserve-penalty', label: 'Armor reserve penalty', scope: 'local-base', valueKind: 'flat', tags: ['defense'], description: 'Reduces armor reserve supplied by this equipment frame.' },
  { id: 'local.movement-speed', label: 'Movement speed', scope: 'local-base', valueKind: 'percent', tags: ['mobility', 'low-g'], description: 'Raises operator movement speed through this equipment frame.' },
  { id: 'local.movement-speed-penalty', label: 'Movement speed penalty', scope: 'local-base', valueKind: 'percent', tags: ['mobility'], description: 'Reduces operator movement speed through this equipment frame.' },
  { id: 'local.capacitor-reserve', label: 'Capacitor reserve', scope: 'local-base', valueKind: 'flat', tags: ['capacitor', 'systems'], description: 'Adds capacitor reserve supplied by this systems frame.' },
  { id: 'local.capacitor-reserve-penalty', label: 'Capacitor reserve penalty', scope: 'local-base', valueKind: 'flat', tags: ['capacitor', 'systems'], description: 'Reduces capacitor reserve supplied by this systems frame.' },
  { id: 'local.capacitor-regeneration', label: 'Capacitor regeneration', scope: 'local-base', valueKind: 'percent', tags: ['capacitor', 'systems'], description: 'Raises capacitor regeneration supplied by this systems frame.' },
  { id: 'local.ability-cost-penalty', label: 'Ability cost penalty', scope: 'local-base', valueKind: 'percent', tags: ['capacitor', 'systems'], description: 'Raises ability capacitor cost while this frame is equipped.' },
  { id: 'local.ability-cooldown', label: 'Ability cooldown', scope: 'local-base', valueKind: 'percent', tags: ['cooldown', 'systems'], description: 'Shortens ability recovery through this systems frame.' },
  { id: 'environment.pressure-resistance', label: 'Pressure resistance', scope: 'environment', valueKind: 'percent', tags: ['pressure', 'vacuum', 'defense'], description: 'Improves resistance to pressure loss and decompression effects.' },
  { id: 'environment.pressure-resistance-penalty', label: 'Pressure resistance penalty', scope: 'environment', valueKind: 'percent', tags: ['pressure', 'vacuum'], description: 'Reduces passive pressure and decompression resistance.' },
  { id: 'environment.low-g-control', label: 'Low-G control', scope: 'environment', valueKind: 'percent', tags: ['mobility', 'low-g', 'recoil'], description: 'Improves braking and vector control in reduced gravity.' },
  { id: 'environment.vacuum-resistance', label: 'Vacuum resistance', scope: 'environment', valueKind: 'percent', tags: ['vacuum', 'pressure', 'defense'], description: 'Reduces vacuum exposure and decompression pull.' },
  { id: 'global.projectile-velocity', label: 'Global projectile velocity', scope: 'global', valueKind: 'percent', tags: ['precision', 'projectile', 'ballistics'], description: 'Raises projectile velocity across compatible weapons.' },
  { id: 'global.penetration', label: 'Global penetration', scope: 'global', valueKind: 'flat', tags: ['penetration', 'armor-break', 'precision'], description: 'Adds penetration across compatible weapons.' },
  { id: 'global.ability-cost-penalty', label: 'Global ability cost penalty', scope: 'global', valueKind: 'percent', tags: ['capacitor', 'systems'], description: 'Raises capacitor cost across operator abilities.' },
  { id: 'global.capacitor-regeneration', label: 'Global capacitor regeneration', scope: 'global', valueKind: 'percent', tags: ['capacitor', 'systems'], description: 'Raises operator capacitor regeneration.' },
  { id: 'global.ability-cost-reduction', label: 'Global ability cost reduction', scope: 'global', valueKind: 'percent', tags: ['capacitor', 'systems', 'cooldown'], description: 'Reduces capacitor cost across operator abilities.' },
  { id: 'global.dodge-vent-rule', label: 'Dodge vent rule', scope: 'global', valueKind: 'rule', tags: ['mobility', 'thermal', 'venting'], description: 'Lets a dodge vent active-weapon heat.' },
  { id: 'skill-family.mark-power', label: 'Mark power', scope: 'skill-family', valueKind: 'percent', tags: ['mark', 'precision', 'armor-break'], description: 'Raises output of the operator mark skill family.' },
  { id: 'skill-family.mark-cooldown-penalty', label: 'Mark cooldown penalty', scope: 'skill-family', valueKind: 'percent', tags: ['mark', 'cooldown'], description: 'Increases recovery time of the operator mark skill family.' },
  { id: 'skill-family.relay-power', label: 'Relay power', scope: 'skill-family', valueKind: 'percent', tags: ['relay', 'disruption', 'systems'], description: 'Raises output of the operator relay skill family.' },
  { id: 'skill-family.relay-cooldown', label: 'Relay cooldown', scope: 'skill-family', valueKind: 'percent', tags: ['relay', 'cooldown', 'systems'], description: 'Shortens recovery of the operator relay skill family.' },
  { id: 'skill-family.relay-cost-penalty', label: 'Relay cost penalty', scope: 'skill-family', valueKind: 'percent', tags: ['relay', 'capacitor', 'systems'], description: 'Raises capacitor cost of the operator relay skill family.' },
  { id: 'skill-family.mag-redirect-rule', label: 'Magnetic redirect rule', scope: 'skill-family', valueKind: 'rule', tags: ['systems', 'disruption', 'projectile'], description: 'Lets Magnetic Impulse capture and redirect hostile projectiles.' },
  { id: 'skill-family.mark-armor-break-rule', label: 'Mark armor-break rule', scope: 'skill-family', valueKind: 'rule', tags: ['mark', 'armor-break', 'precision'], description: 'Lets marked targets expose weak armor paths.' },
  { id: 'skill-family.relay-drone-rule', label: 'Relay microdrone rule', scope: 'skill-family', valueKind: 'rule', tags: ['relay', 'disruption', 'systems'], description: 'Adds a microdrone attack loop against disrupted targets.' },
  { id: 'affix.projectile-velocity', label: 'Projectile velocity modifier', scope: 'local-affix', valueKind: 'percent', tags: ['precision', 'projectile', 'ballistics'], description: 'Explicit modifier that raises projectile velocity on its weapon.' },
  { id: 'affix.penetration', label: 'Penetration modifier', scope: 'local-affix', valueKind: 'flat', tags: ['penetration', 'armor-break', 'precision'], description: 'Explicit modifier that adds penetration on its weapon.' },
  { id: 'affix.penetration-penalty', label: 'Penetration tradeoff', scope: 'local-affix', valueKind: 'flat', tags: ['penetration'], description: 'Explicit modifier tradeoff that removes weapon penetration.' },
  { id: 'affix.recoil-penalty', label: 'Recoil tradeoff', scope: 'local-affix', valueKind: 'percent', tags: ['recoil'], description: 'Explicit modifier tradeoff that raises weapon recoil.' },
  { id: 'affix.recoil-absorption', label: 'Recoil absorption modifier', scope: 'local-affix', valueKind: 'percent', tags: ['recoil', 'precision', 'defense'], description: 'Explicit modifier that reduces weapon recoil.' },
  { id: 'affix.direct-output', label: 'Direct output modifier', scope: 'local-affix', valueKind: 'percent', tags: ['ballistics', 'armor-break'], description: 'Explicit modifier that raises direct weapon output.' },
  { id: 'affix.direct-output-penalty', label: 'Direct output tradeoff', scope: 'local-affix', valueKind: 'percent', tags: ['ballistics'], description: 'Explicit modifier tradeoff that reduces direct weapon output.' },
  { id: 'affix.heat-per-shot-penalty', label: 'Heat per shot tradeoff', scope: 'local-affix', valueKind: 'percent', tags: ['thermal', 'heat'], description: 'Explicit modifier tradeoff that raises shot heat.' },
  { id: 'affix.heat-dissipation', label: 'Heat dissipation modifier', scope: 'local-affix', valueKind: 'percent', tags: ['thermal', 'heat', 'venting'], description: 'Explicit modifier that improves heat rejection.' },
  { id: 'affix.magazine-capacity', label: 'Magazine capacity modifier', scope: 'local-affix', valueKind: 'flat', tags: ['ballistics', 'systems'], description: 'Explicit modifier that increases weapon magazine capacity.' },
  { id: 'affix.reload-time-penalty', label: 'Reload time tradeoff', scope: 'local-affix', valueKind: 'percent', tags: ['ballistics', 'systems'], description: 'Explicit modifier tradeoff that increases reload time.' },
  { id: 'affix.armor-damage', label: 'Armor damage modifier', scope: 'local-affix', valueKind: 'percent', tags: ['armor-break', 'penetration', 'ballistics'], description: 'Explicit modifier that raises damage dealt to armor.' },
  { id: 'affix.movement-speed', label: 'Movement speed modifier', scope: 'local-affix', valueKind: 'percent', tags: ['mobility', 'low-g'], description: 'Explicit modifier that raises operator movement speed.' },
  { id: 'affix.rail-fracture-rule', label: 'Rail fracture rule', scope: 'local-affix', valueKind: 'rule', tags: ['precision', 'projectile', 'armor-break'], description: 'Adds post-penetration rail fragmentation.' },
  { id: 'affix.breacher-propulsion-rule', label: 'Breacher propulsion rule', scope: 'local-affix', valueKind: 'rule', tags: ['recoil', 'mobility', 'low-g'], description: 'Converts Breacher discharge impulse into mobility.' },
] as const satisfies readonly GearStatSeed[];

export type GearStatId = (typeof gearStatDefinitions)[number]['id'];
export type GearStatDefinition = {
  id: GearStatId;
  label: string;
  scope: GearStatScope;
  valueKind: GearStatValueKind;
  tags: readonly GearBuildTag[];
  description: string;
};

const statById = new Map<GearStatId, GearStatDefinition>(
  gearStatDefinitions.map(definition => [definition.id, definition as GearStatDefinition]),
);

export function gearStatDefinition(id: GearStatId) {
  const definition = statById.get(id);
  if (!definition) throw new Error(`Unknown gear stat: ${id}`);
  return definition;
}

export function mergeBuildTags(...groups: ReadonlyArray<readonly GearBuildTag[]>) {
  const tags = new Set(groups.flat());
  return gearBuildTags.filter(tag => tags.has(tag));
}

export function buildTagsForStats(ids: readonly GearStatId[]) {
  return mergeBuildTags(...ids.map(id => gearStatDefinition(id).tags));
}

export const gearAffixSemanticIds = [
  'hypervelocity', 'countermass', 'overdrive', 'cryoloop', 'extendedFeed', 'tungsten',
  'vacuumSeal', 'servoWeave', 'capacitorRecycler', 'railFracture', 'dodgeVent',
  'magRedirect', 'breachPropulsion', 'markShear', 'arcDrone',
] as const;
export type GearAffixSemanticId = (typeof gearAffixSemanticIds)[number];

type AffixProfileSeed = {
  stats: readonly GearStatId[];
  tradeoffs: readonly GearStatId[];
  classAffinities: readonly GearClassAffinity[];
};

const affixStatProfiles = {
  hypervelocity: { stats: ['affix.projectile-velocity', 'affix.penetration'], tradeoffs: ['affix.recoil-penalty'], classAffinities: ['vector'] },
  countermass: { stats: ['affix.recoil-absorption'], tradeoffs: ['affix.direct-output-penalty'], classAffinities: ['vector'] },
  overdrive: { stats: ['affix.direct-output'], tradeoffs: ['affix.recoil-penalty', 'affix.heat-per-shot-penalty'], classAffinities: ['vanguard'] },
  cryoloop: { stats: ['affix.heat-dissipation'], tradeoffs: ['affix.penetration-penalty'], classAffinities: ['systems'] },
  extendedFeed: { stats: ['affix.magazine-capacity'], tradeoffs: ['affix.reload-time-penalty'], classAffinities: ['vanguard', 'systems'] },
  tungsten: { stats: ['affix.armor-damage', 'affix.penetration'], tradeoffs: ['affix.heat-per-shot-penalty'], classAffinities: ['vanguard'] },
  vacuumSeal: { stats: ['environment.vacuum-resistance'], tradeoffs: [], classAffinities: ['vanguard'] },
  servoWeave: { stats: ['affix.movement-speed', 'environment.low-g-control'], tradeoffs: [], classAffinities: ['vector'] },
  capacitorRecycler: { stats: ['global.capacitor-regeneration', 'global.ability-cost-reduction'], tradeoffs: [], classAffinities: ['systems'] },
  railFracture: { stats: ['affix.rail-fracture-rule'], tradeoffs: [], classAffinities: ['vector'] },
  dodgeVent: { stats: ['global.dodge-vent-rule'], tradeoffs: [], classAffinities: ['vector'] },
  magRedirect: { stats: ['skill-family.mag-redirect-rule'], tradeoffs: [], classAffinities: ['systems'] },
  breachPropulsion: { stats: ['affix.breacher-propulsion-rule'], tradeoffs: [], classAffinities: ['vanguard'] },
  markShear: { stats: ['skill-family.mark-armor-break-rule'], tradeoffs: [], classAffinities: ['vector'] },
  arcDrone: { stats: ['skill-family.relay-drone-rule'], tradeoffs: [], classAffinities: ['systems'] },
} as const satisfies Record<GearAffixSemanticId, AffixProfileSeed>;

export function affixStatProfile(id: GearAffixSemanticId) {
  const profile = affixStatProfiles[id];
  return {
    ...profile,
    buildTags: buildTagsForStats(profile.stats),
  };
}

export function validateGearStatRegistry() {
  const ids = new Set(gearStatDefinitions.map(definition => definition.id));
  const validTags = new Set<string>(gearBuildTags);
  const validScopes = new Set<GearStatScope>(['local-base', 'local-affix', 'global', 'skill-family', 'environment']);
  const validKinds = new Set<GearStatValueKind>(['flat', 'percent', 'multiplier', 'boolean', 'rule']);
  return ids.size === gearStatDefinitions.length
    && gearStatDefinitions.every(definition => definition.tags.length > 0
      && definition.tags.every(tag => validTags.has(tag))
      && validScopes.has(definition.scope)
      && validKinds.has(definition.valueKind))
    && gearAffixSemanticIds.every(id => {
      const profile = affixStatProfile(id);
      return profile.stats.length > 0
        && [...profile.stats, ...profile.tradeoffs].every(statId => ids.has(statId))
        && profile.buildTags.length > 0
        && profile.classAffinities.length > 0;
    });
}
