import type { SingularTraitId } from './sim';

export const gearSingularCategories = [
  'skill-transformer',
  'resource-loop',
  'movement-transformer',
  'projectile-transformer',
  'defense-transformer',
  'conditional-engine',
  'build-converter',
  'environmental-interaction',
] as const;

export type GearSingularCategory = (typeof gearSingularCategories)[number];
export type GearSingularSlot = 'carbine' | 'breacher' | 'rail' | 'suit' | 'rig' | 'implant';

export type GearSingularChaseDefinition = {
  baseId: string;
  name: string;
  slot: GearSingularSlot;
  singularTrait: SingularTraitId;
  category: GearSingularCategory;
  rule: string;
  opportunityCost: string;
};

export const singularChaseDefinitions = [
  { baseId: "voss-palisade-m7", name: "Palisade Doctrine M-7", slot: "carbine", singularTrait: "palisadeDoctrine", category: "defense-transformer", rule: "Stationary carbine fire rebuilds small amounts of armor, rewarding deliberate firing positions.", opportunityCost: "Armor recovery requires stationary carbine fire, trading mobility and dodge freedom for sustain." },
  { baseId: "voss-pressure-mantle", name: "Compact Pressure Mantle", slot: "suit", singularTrait: "pressureMantle", category: "defense-transformer", rule: "Cycling pressure controls or sealing a rupture restores armor and clears vacuum exposure.", opportunityCost: "Its recovery loop only triggers from pressure-control or seal actions, so ordinary combat provides no free armor reset." },
  { baseId: "voss-lockstep-rig", name: "Lockstep Command Rig", slot: "rig", singularTrait: "lockstepArc", category: "skill-transformer", rule: "Cascade Arc through machinery restores armor and capacitor while propagating disruption.", opportunityCost: "The payoff requires Cascade Arc to route through machinery, tying sustain to environmental setup instead of raw stats." },
  { baseId: "rhea-backblast-b4", name: "Rhea's Backblast Kestrel", slot: "breacher", singularTrait: "rheaBackblast", category: "movement-transformer", rule: "Breacher shots produce extreme controlled backblast and accelerate the next dodge cycle.", opportunityCost: "Every boosted discharge creates major operator displacement, so the player must spend positioning to exploit the mobility gain." },
  { baseId: "rhea-tether-link", name: "Tetherhand Sensor Link", slot: "implant", singularTrait: "tetherhand", category: "skill-transformer", rule: "Your second class skill leaves a short magnetic tether well on the marked target.", opportunityCost: "The tether exists only after a successful second class skill and remains tied to that marked target." },
  { baseId: "rhea-scrapline-suit", name: "Scrapline Countermass Suit", slot: "suit", singularTrait: "scraplineDodge", category: "movement-transformer", rule: "Dodges below 0.35g travel farther and recover faster, turning low gravity into an offensive resource.", opportunityCost: "The enhanced dodge only exists below 0.35g, leaving the suit without its chase rule in normal gravity." },
  { baseId: "helios-thermal-governor", name: "HELIOS-9 Thermal Governor", slot: "rig", singularTrait: "thermalGovernor", category: "resource-loop", rule: "Manual venting dumps heat from every weapon and advances all ability cooldowns.", opportunityCost: "The cooldown dividend requires a manual vent, which interrupts firing and commits the operator to a thermal reset window." },
  { baseId: "helios-machine-sight", name: "Machine-Sight Cognition Node", slot: "implant", singularTrait: "machineSight", category: "skill-transformer", rule: "Cascade Arc through machinery seeks an additional disrupted target beyond the normal propagation radius.", opportunityCost: "The extra Cascade Arc target requires both machinery routing and a disrupted follow-up target, so it is not unconditional chain damage." },
  { baseId: "helios-fracture-rails", name: "Sunward Fracture Rails", slot: "rail", singularTrait: "sunwardFracture", category: "projectile-transformer", rule: "High-heat Rail Lance shots split into two narrow secondary vectors at the muzzle.", opportunityCost: "The split only appears at high Rail heat, forcing deliberate redline exposure and thermal recovery afterward." },
  { baseId: "vale-vector-spool-m11", name: "Vale Vector-Spool M-11", slot: "carbine", singularTrait: "inertiaSpool", category: "conditional-engine", rule: "While moving fast across the aim line, carbine fire gains damage and velocity while shedding most recoil.", opportunityCost: "The receiver only stabilizes during fast lateral movement across the aim line, so direct approaches and stationary fire lose the effect." },
  { baseId: "vale-clutchstep-harness", name: "Clutchstep Countermass Harness", slot: "suit", singularTrait: "clutchstep", category: "environmental-interaction", rule: "Dodging near a gravity or countermass field consumes it, restores capacitor, and shortens dodge recovery.", opportunityCost: "The dodge consumes a nearby gravity or countermass field, exchanging future field utility for immediate capacitor and recovery." },
  { baseId: "vale-flywheel-ledger-rig", name: "Flywheel Ledger Rig", slot: "rig", singularTrait: "recoilLedger", category: "build-converter", rule: "Rail shots refund capacitor but produce substantially more recoil, turning every lance into a movement commitment.", opportunityCost: "Rail shots return capacitor but create substantially more recoil, making every shot a movement and aim-control commitment." },
  { baseId: "saal-cold-start-kestrel", name: "Umbra Cold-Start Kestrel", slot: "breacher", singularTrait: "coldStartBreach", category: "conditional-engine", rule: "A Breacher shot from a cold bus gains damage, penetration, and velocity but adds extra heat.", opportunityCost: "The empowered cold-bus shot adds extra heat, front-loading power at the cost of a steeper thermal follow-up." },
  { baseId: "saal-purgewake-rig", name: "Purgewake Thermal Rig", slot: "rig", singularTrait: "purgeWake", category: "environmental-interaction", rule: "Manual venting below 45% pressure emits a player-owned coolant thrust plume that pushes and staggers enemies.", opportunityCost: "The plume requires both low pressure and a manual vent, committing the player to a vulnerable reset instead of granting passive crowd control." },
  { baseId: "saal-grid-reclaimer-link", name: "Saal Grid-Reclaimer Link", slot: "implant", singularTrait: "gridReclaimer", category: "environmental-interaction", rule: "Cascade Arc through machinery can collapse a nearby hostile shock grid, restoring capacitor and cooling the active weapon.", opportunityCost: "The recovery requires machinery routing plus a nearby hostile shock grid, and collapsing that grid consumes the environmental interaction." },
  { baseId: "teth-custody-shear-optics", name: "Custody Shear Optics", slot: "implant", singularTrait: "custodyShear", category: "environmental-interaction", rule: "Your second class skill forces a marked objective carrier to drop mission hardware immediately and can strip nearby hostile support relays.", opportunityCost: "The rule needs a marked objective carrier or nearby support relay; ordinary targets provide no special payoff." },
  { baseId: "teth-shutterline-r6", name: "Shutterline R-6", slot: "rail", singularTrait: "shutterLine", category: "projectile-transformer", rule: "Rail rounds punch through destructible non-bulkhead cover without their normal damage loss and gain penetration and velocity.", opportunityCost: "The penetration rewrite only applies to destructible non-bulkhead cover, so open sightlines and true bulkheads gain no benefit." },
  { baseId: "teth-archive-relay-dynamo", name: "Archive Relay Dynamo", slot: "rig", singularTrait: "archiveRelay", category: "environmental-interaction", rule: "Destroying cover or machinery emits an Arc pulse that disrupts and conducts nearby enemies.", opportunityCost: "The Arc pulse requires destroying cover or machinery, exchanging battlefield geometry for a temporary offensive chain." },
  { baseId: "nox-parallax-r7", name: "Nox Parallax R-7", slot: "rail", singularTrait: "nullpoint", category: "conditional-engine", rule: "Rail hits during committed hostile telegraphs cancel the firing solution and refund capacitor.", opportunityCost: "The interrupt and refund require a Rail hit during the hostile telegraph commitment window; mistimed shots gain nothing." },
  { baseId: "nox-baseline-debt-rig", name: "Baseline Debt Rig", slot: "rig", singularTrait: "recoilLedger", category: "build-converter", rule: "Rail shots refund capacitor but produce substantially more recoil, making every shot a movement decision.", opportunityCost: "Rail shots return capacitor but create substantially more recoil, making every shot a movement and aim-control commitment." },
  { baseId: "nox-blind-meridian-link", name: "Blind Meridian Link", slot: "implant", singularTrait: "splitReference", category: "skill-transformer", rule: "Cascade Arc on a marked target consumes the mark and can relay through nearby machinery into a second enemy.", opportunityCost: "The Cascade Arc relay consumes the active mark and requires nearby machinery, trading target persistence for a second electrical origin." },
  { baseId: "khepri-null-rails", name: "Khepri Null-Reference Rails", slot: "rail", singularTrait: "nullpoint", category: "conditional-engine", rule: "Rail hits during an enemy telegraph cancel that attack and refund capacitor.", opportunityCost: "The interrupt and refund require a Rail hit during the hostile telegraph commitment window; mistimed shots gain nothing." },
  { baseId: "khepri-vector-harness", name: "Khepri Calibration Harness", slot: "suit", singularTrait: "atlasDodgeCap", category: "build-converter", rule: "Dodging converts pre-dodge movement speed into capacitor charge.", opportunityCost: "The conversion only pays when the operator enters the dodge with real movement speed, making standing dodges inefficient." },
  { baseId: "khepri-surveyor-node", name: "Surveyor Relay Cognition Node", slot: "implant", singularTrait: "relayCrown", category: "skill-transformer", rule: "Your second class skill jumps through nearby exposed machinery to additional enemies around that machine.", opportunityCost: "The jump requires exposed machinery near the target; open rooms without a relay provide no extra targets." },
  { baseId: "vacuum-choir-rails", name: "Vacuum Choir Rails", slot: "rail", singularTrait: "vacuumWake", category: "projectile-transformer", rule: "Rail shots create a temporary low-pressure wake that pulls, staggers, and abrades nearby enemies.", opportunityCost: "The wake is positional and temporary, so the item gives up unconditional single-target power for lane control." },
  { baseId: "atlas-countermass-harness", name: "Atlas Countermass Harness", slot: "suit", singularTrait: "atlasDodgeCap", category: "build-converter", rule: "Dodging converts pre-dodge movement speed into capacitor charge.", opportunityCost: "The conversion only pays when the operator enters the dodge with real movement speed, making standing dodges inefficient." },
  { baseId: "redline-kestrel", name: "Redline Kestrel", slot: "breacher", singularTrait: "redlineVelocity", category: "conditional-engine", rule: "Breacher pellet damage scales with current operator velocity at the instant of firing.", opportunityCost: "Damage depends on committed movement at trigger time, so stationary or poorly aligned shots lose the Singular payoff." },
  { baseId: "long-arc-relay-crown", name: "Long Arc Relay Crown", slot: "implant", singularTrait: "relayCrown", category: "skill-transformer", rule: "Your second class skill jumps through nearby exposed machinery to additional enemies around that machine.", opportunityCost: "The jump requires exposed machinery near the target; open rooms without a relay provide no extra targets." },
  { baseId: "arcspindle-m7", name: "Arcspindle M-7", slot: "carbine", singularTrait: "arcspindle", category: "resource-loop", rule: "Carbine hits against disrupted or conductive enemies return capacitor charge.", opportunityCost: "Capacitor return only occurs against disrupted or conductive enemies, requiring setup before the loop starts." },
  { baseId: "ghostline-m7", name: "Ghostline M-7", slot: "carbine", singularTrait: "ghostline", category: "conditional-engine", rule: "Below 35% pressure, carbine rounds gain major velocity and penetration while recoil collapses.", opportunityCost: "The ballistic advantage only exists below 35% pressure, so normal-pressure encounters receive no chase bonus." },
  { baseId: "borecutter-m7", name: "Borecutter M-7", slot: "carbine", singularTrait: "borecutter", category: "environmental-interaction", rule: "Player fire deals greatly increased damage to destructible cover and machinery.", opportunityCost: "The rule improves object destruction rather than direct enemy damage, so it pays only where cover or machinery can be exploited." },
  { baseId: "stormline-ventgun", name: "Stormline Ventgun", slot: "breacher", singularTrait: "stormVentgun", category: "conditional-engine", rule: "Breacher fire near an active breach gains damage and knockback while shedding some heat.", opportunityCost: "The bonus requires firing near an active breach, trading safe positioning for pressure-lane access." },
  { baseId: "nullpoint-needle", name: "Nullpoint Needle", slot: "rail", singularTrait: "nullpoint", category: "conditional-engine", rule: "Rail hits during an enemy telegraph cancel that attack and refund capacitor.", opportunityCost: "The interrupt and refund require a Rail hit during the hostile telegraph commitment window; mistimed shots gain nothing." },
  { baseId: "glasswalker-eva", name: "Glasswalker EVA Skin", slot: "suit", singularTrait: "glasswalker", category: "movement-transformer", rule: "In near-vacuum, acceleration and maximum movement speed increase instead of collapsing into cautious footing.", opportunityCost: "The movement rewrite only activates in near-vacuum, so pressurized sectors provide no mobility advantage." },
  { baseId: "cryostack-burn-rig", name: "Cryostack Burn Rig", slot: "rig", singularTrait: "cryostack", category: "resource-loop", rule: "Crossing into weapon overheat advances all ability cooldowns, rewarding deliberate redline bursts.", opportunityCost: "The player must deliberately cross into overheat to trigger the cooldown dividend, accepting the normal redline lockout risk." },
  { baseId: "salvage-dynamo-rig", name: "Salvage Dynamo Rig", slot: "rig", singularTrait: "salvageDynamo", category: "resource-loop", rule: "Destroying destructible cover or machinery restores capacitor and cools the current weapon.", opportunityCost: "The recovery loop only starts when destructible cover or machinery is destroyed, so empty arenas provide no benefit." },
  { baseId: "deadreckon-optics", name: "Deadreckon Optics", slot: "implant", singularTrait: "deadreckon", category: "skill-transformer", rule: "Killing a marked enemy nearly resets your second class skill.", opportunityCost: "The reset requires a marked kill, making failed kill confirms or unmarked targets break the chain." },
  { baseId: "jovian-stormskin", name: "Jovian Stormskin", slot: "suit", singularTrait: "stormskin", category: "defense-transformer", rule: "Shock-grid damage is heavily reduced and partially converted into capacitor charge.", opportunityCost: "Its defense conversion only applies to shock-grid damage and does not reduce ordinary weapon or melee pressure." },
  { baseId: "axis-ghost-rig", name: "Axis Ghost Rig", slot: "rig", singularTrait: "axisGhost", category: "movement-transformer", rule: "Dodging below 0.12g emits a radial impulse that throws nearby enemies away.", opportunityCost: "The radial impulse only triggers below 0.12g, making it a specialized zero-g control tool instead of universal dodge power." },
  { baseId: "pendulum-kestrel", name: "Pendulum Kestrel", slot: "breacher", singularTrait: "pendulumBreach", category: "build-converter", rule: "Firing the Breacher against your current direction of travel brakes momentum, amplifies the shot, and returns capacitor charge.", opportunityCost: "The empowered shot must oppose current travel and brakes the operator, converting mobility into damage and capacitor rather than preserving both." },
  { baseId: "mass-return-crown", name: "Mass-Return Crown", slot: "implant", singularTrait: "massTap", category: "environmental-interaction", rule: "Your first class skill consumes one nearby gravity/countermass field and converts it into capacitor charge.", opportunityCost: "Your first class skill consumes a nearby gravity or countermass field, permanently spending that environmental resource for the encounter." },
  { baseId: "umbra-heatsink-rig", name: "Umbra Heat-Sink Rig", slot: "rig", singularTrait: "boiloffSink", category: "environmental-interaction", rule: "Coolant and boiloff plumes cool all weapons and convert the normal boiloff capacitor loss into charge.", opportunityCost: "The conversion requires contact with coolant or boiloff plumes, so it depends on dangerous environmental geometry." },
  { baseId: "cryoline-reference-rails", name: "Cryoline Reference Rails", slot: "rail", singularTrait: "cryolineRail", category: "conditional-engine", rule: "Rail shots fired from a cold weapon bus gain major damage and penetration, rewarding deliberate thermal resets.", opportunityCost: "The bonus only applies to a cold Rail bus, rewarding full thermal resets instead of sustained firing." },
  { baseId: "breathless-choir-mantle", name: "Breathless Choir Mantle", slot: "suit", singularTrait: "pressureReservoir", category: "movement-transformer", rule: "Dodging below 35% pressure spends 8 capacitor to leave a short player-owned low-pressure wake; no charge means no wake.", opportunityCost: "The wake only forms below 35% pressure and costs 8 capacitor, so repeated mobility directly competes with ability resources." },
  { baseId: "vector-debt-m12", name: "Vector Debt M-12", slot: "carbine", singularTrait: "recoilDynamo", category: "build-converter", rule: "Carbine recoil is amplified but converted into a capped capacitor return on each shot; it never stacks additively with other recoil refunds.", opportunityCost: "Carbine recoil is deliberately amplified to earn the capacitor return, trading handling comfort for resource generation." },
  { baseId: "relay-orchard-node", name: "Relay Orchard Node", slot: "implant", singularTrait: "relayOrchard", category: "skill-transformer", rule: "Cascade Arc through machinery marks up to two nearby enemies and trims Relay Hack recovery.", opportunityCost: "The mark spread requires Cascade Arc routing through machinery, making the skill loop dependent on exposed environmental relays." },
  { baseId: "cold-witness-r7", name: "Cold Witness R-7", slot: "rail", singularTrait: "coldWitness", category: "skill-transformer", rule: "A Rail hit consumes an active mark, cools the rail bus, and leaves a short Armor Breach window.", opportunityCost: "The Rail follow-up consumes the active mark, trading persistent targeting information for cooling and an Armor Breach window." },
  { baseId: "radiant-liability-kestrel", name: "Radiant Liability Kestrel", slot: "breacher", singularTrait: "redlineBulwark", category: "defense-transformer", rule: "Breacher hits above 75% heat rebuild small amounts of armor, but each redline shot adds extra heat.", opportunityCost: "The armor return only works above 75% heat and each qualifying Breacher shot adds extra heat, accelerating overheat risk." },
  { baseId: "palisade-breaker-b9", name: "Palisade Breaker B-9", slot: "breacher", singularTrait: "closeBreach", category: "build-converter", rule: "Inside 300 units, Breacher pellets gain a capped armor-damage conversion but lose direct-health efficiency.", opportunityCost: "The close-range conversion gains armor demolition but loses direct-health efficiency, specializing the weapon away from universal damage." },
  { baseId: "capacitor-rosary-rig", name: "Capacitor Rosary Rig", slot: "rig", singularTrait: "abilityRosary", category: "resource-loop", rule: "Using a different ability within the combo window cools the active weapon and trims the previous ability recovery.", opportunityCost: "The rig rewards rotating to a different ability inside the combo window, so repeating one favored skill breaks the loop." },
  { baseId: "vacuum-psalm-m12", name: "Vacuum Psalm M-12", slot: "carbine", singularTrait: "pressureBallistics", category: "projectile-transformer", rule: "Below 45% pressure, carbine rounds gain velocity and penetration; above 75% pressure, projectile velocity is reduced.", opportunityCost: "Thin pressure improves ballistics, but above 75% pressure projectile velocity is explicitly reduced." },
  { baseId: "falling-star-harness", name: "Falling Star Harness", slot: "suit", singularTrait: "momentumMark", category: "movement-transformer", rule: "Dodging with high pre-dodge speed spends 6 capacitor to mark the nearest visible enemy.", opportunityCost: "The auto-mark requires high pre-dodge speed and spends 6 capacitor, turning movement into targeting at a resource cost." },
  { baseId: "scrap-circuit-rig", name: "Scrap Circuit Rig", slot: "rig", singularTrait: "scrapCircuit", category: "resource-loop", rule: "Destroying machinery spends 4 capacitor to advance your third class skill recovery by 0.9 seconds.", opportunityCost: "The third-skill recovery requires machinery destruction and spends 4 capacitor, so the player must decide whether the tempo gain is worth the bus cost." },
  { baseId: "eventide-eva-skin", name: "Eventide EVA Skin", slot: "suit", singularTrait: "boiloffDash", category: "movement-transformer", rule: "Dodging through a nearby coolant or boiloff plume spends 8 capacitor, consumes one plume, extends the dash, and cools all weapons.", opportunityCost: "The extended dodge costs 8 capacitor and consumes one coolant or boiloff plume, spending both resource and environmental setup." },
  { baseId: "khepri-split-reference-link", name: "Khepri Split-Reference Link", slot: "implant", singularTrait: "splitReference", category: "skill-transformer", rule: "Cascade Arc on a marked target consumes the mark and can relay through nearby machinery into a second enemy.", opportunityCost: "The Cascade Arc relay consumes the active mark and requires nearby machinery, trading target persistence for a second electrical origin." },
  { baseId: "sixth-vector-m12", name: "Sixth-Vector M-12", slot: "carbine", singularTrait: "forkedSpool", category: "projectile-transformer", rule: "Every sixth Carbine shot forks two 55% side vectors. The forked shot adds extra heat, rewarding deliberate cadence rather than permanent free damage.", opportunityCost: "Only every sixth Carbine shot forks and that shot adds extra heat, creating a cadence and thermal obligation instead of passive extra projectiles." },
  { baseId: "backstep-kestrel-b9", name: "Backstep Kestrel B-9", slot: "breacher", singularTrait: "breachEcho", category: "projectile-transformer", rule: "A Breacher shot within 0.65s of a dodge gains a three-pellet 55% echo cone, but the echoed shot adds extra heat.", opportunityCost: "The echo only exists within 0.65 seconds after a dodge and the echoed shot adds extra heat, tying burst damage to evasive timing." },
  { baseId: "cold-doublet-r7", name: "Cold Doublet R-7", slot: "rail", singularTrait: "railDoublet", category: "projectile-transformer", rule: "Below 22% Rail heat and with 8 spare capacitor, each Rail shot launches a second 58% penetrator. The doublet consumes the extra capacitor and adds heat.", opportunityCost: "The second penetrator requires a cold Rail bus plus 8 spare capacitor and adds heat, so sustained firing disables the rule." },
  { baseId: "bloom-vector-rig", name: "Bloom Vector Rig", slot: "rig", singularTrait: "magBloom", category: "skill-transformer", rule: "Your first class skill fires eight radial kinetic micro-slugs after resolving. That skill costs 25% more capacitor and recovers 8% slower.", opportunityCost: "The first class skill gains the radial slug bloom but costs 25% more capacitor and recovers 8% slower." },
  { baseId: "cascade-sight-link", name: "Cascade Sight Link", slot: "implant", singularTrait: "markCascade", category: "skill-transformer", rule: "Killing a target marked by your second class skill relays a 4.2s mark to a nearby enemy. Initial second-skill marks are shorter and the skill recovers 12% slower.", opportunityCost: "Relayed marks require a marked kill, while initial second-skill marks are shorter and the skill recovers 12% slower." },
] as const satisfies readonly GearSingularChaseDefinition[];

const singularByBaseId = new Map<string, GearSingularChaseDefinition>(
  singularChaseDefinitions.map(definition => [definition.baseId, definition]),
);

export function singularChaseDefinition(baseId: string) {
  return singularByBaseId.get(baseId);
}

export function validateSingularChaseRegistry() {
  if (singularByBaseId.size !== singularChaseDefinitions.length) return false;
  const categories = new Set(gearSingularCategories);
  return singularChaseDefinitions.every(definition =>
    categories.has(definition.category)
    && definition.rule.trim().length > 0
    && definition.opportunityCost.trim().length > 0
  );
}
