import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { GRAPHICS_ASSET_STANDARDS, createGraphicsAssetSpec, graphicsAssetLodForDetailScale, selectGraphicsAssetSpec, validateGraphicsAssetSpec, type GraphicsAssetFamily } from '../src/game/graphicsAssets';
function assert(condition: unknown, message: string) { if (!condition) throw new Error(message); }
assert(GRAPHICS_ASSET_STANDARDS.runtimeFormat==='glb' && GRAPHICS_ASSET_STANDARDS.unitScaleMeters===1 && GRAPHICS_ASSET_STANDARDS.upAxis==='+Y' && GRAPHICS_ASSET_STANDARDS.forwardAxis==='+X','authored runtime asset coordinate/format contract changed');
assert(GRAPHICS_ASSET_STANDARDS.compression.mesh==='meshopt' && GRAPHICS_ASSET_STANDARDS.compression.texture==='ktx2','mobile compression targets must remain meshopt+ktx2');
assert(GRAPHICS_ASSET_STANDARDS.maxTextureDimension.operator<=2048 && GRAPHICS_ASSET_STANDARDS.maxTextureDimension.enemy<=1024,'texture caps must remain mobile-safe');
const operator=createGraphicsAssetSpec('operator-meridian-lod0','operator','/assets/models/operators/operator-meridian-lod0.glb');
assert(validateGraphicsAssetSpec(operator).length===0 && operator.triangleBudget===45000 && operator.compressedByteBudget===2500000,'valid operator GLB contract rejected or budget drifted');
assert(validateGraphicsAssetSpec(createGraphicsAssetSpec('Operator Meridian','operator','/assets/models/operators/operator-meridian-lod0.glb')).some(issue=>issue.includes('kebab-case')),'invalid asset id should be rejected');
assert(validateGraphicsAssetSpec(createGraphicsAssetSpec('operator-meridian-lod0','operator','/models/operator-meridian-lod0.glb')).some(issue=>issue.includes('/assets/models/')),'asset outside model root should be rejected');
assert(graphicsAssetLodForDetailScale(1)===0 && graphicsAssetLodForDetailScale(0.72)===1 && graphicsAssetLodForDetailScale(0.5)===2,'adaptive LOD thresholds changed');
const family:GraphicsAssetFamily={id:'test',lods:{1:createGraphicsAssetSpec('test-lod1','enemy','/assets/models/enemies/test-lod1.glb',1),2:createGraphicsAssetSpec('test-lod2','enemy','/assets/models/enemies/test-lod2.glb',2)}};
assert(selectGraphicsAssetSpec(family,1)?.lod===1 && selectGraphicsAssetSpec(family,0.5)?.lod===2,'LOD selection fallback must remain deterministic');
const contractSource=readFileSync(resolve(process.cwd(),'src/game/graphicsAssets.ts'),'utf8');
const runtimeSource=readFileSync(resolve(process.cwd(),'src/game/babylonGraphicsAssets.ts'),'utf8');
const loaderSource=readFileSync(resolve(process.cwd(),'src/game/babylonGltfLoader.ts'),'utf8');
const manifestSource=readFileSync(resolve(process.cwd(),'src/game/graphicsAssetManifest.ts'),'utf8');
const rendererSource=readFileSync(resolve(process.cwd(),'src/game/babylonCombatRenderer.ts'),'utf8');
const prepareCodecs=readFileSync(resolve(process.cwd(),'scripts/prepare-graphics-codecs.mjs'),'utf8');
assert(!contractSource.includes("from 'three'") && !contractSource.includes('@babylonjs/'),'shared graphics asset contract must remain renderer-neutral');
assert(runtimeSource.includes("import('./babylonGltfLoader')") && loaderSource.includes("import '@babylonjs/loaders/glTF/2.0/glTFLoader'"),'Babylon GLB loader must remain deferred and scoped to glTF 2.0');
assert(runtimeSource.includes('BABYLON_GRAPHICS_CODEC_PATHS') && !runtimeSource.includes('cdn.babylonjs.com') && !runtimeSource.includes('preview.babylonjs.com'),'Babylon decoder configuration must stay local');
assert(runtimeSource.includes('async preload(specs: readonly GraphicsAssetSpec[]') && runtimeSource.includes('instantiateModelsToScene') && runtimeSource.includes('entry.activeInstances === 0'),'Babylon runtime must provide bounded preload, instantiation, and safe cache eviction');
assert(prepareCodecs.includes("public/assets/codecs/babylon") && !prepareCodecs.includes('node_modules/three'),'codec preparation must be Babylon-only');
for (const token of ['OPERATOR_ASSET_FAMILY','OPERATOR_CLASS_ASSET_FAMILIES','ENEMY_ASSET_FAMILIES','WEAPON_ASSET_FAMILIES','REFINERY_ASSET_FAMILIES','PICKUP_ASSET_FAMILY','INTERACTABLE_ASSET_FAMILIES']) assert(manifestSource.includes(token),`graphics manifest missing ${token}`);
assert(rendererSource.includes("from './graphicsAssetManifest'") && rendererSource.includes("from './graphicsAssets'") && rendererSource.includes("from './babylonGraphicsAssets'"),'Babylon combat renderer must consume shared manifest/contract through Babylon runtime');
assert(rendererSource.includes('runtime.preload(') && rendererSource.includes('runtime.instantiate('),'Babylon combat renderer must use the shared cached asset runtime');
assert(rendererSource.includes("dataset.operatorVisual = 'authored-fallback-babylon'") && rendererSource.includes("dataset.weaponVisual = 'authored-fallback-babylon'") && rendererSource.includes("dataset.environmentVisual = 'authored-fallback-babylon'"),'authored asset failures must preserve Babylon procedural presentation fallbacks');
console.log('GRAPHICS_ASSET_PIPELINE_PASS contract=renderer-neutral runtime=babylon codecs=local lod=adaptive cache=bounded fallbacks=preserved');
