import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { clampRefineryBloomCostScale, isRefineryBloomAssetLabel, REFINERY_BLOOM_PROFILE, refineryBloomResolutionScale, refineryBloomStrengthForCost } from '../src/game/refineryBloomProfile';
function assert(condition: unknown, message: string) { if (!condition) throw new Error(message); }
assert(REFINERY_BLOOM_PROFILE.strength > 0 && REFINERY_BLOOM_PROFILE.strength < 0.7, 'bloom strength must stay bounded');
assert(REFINERY_BLOOM_PROFILE.radius > 0 && REFINERY_BLOOM_PROFILE.radius < 0.5, 'bloom radius must stay bounded');
assert(clampRefineryBloomCostScale(-1) === 0 && clampRefineryBloomCostScale(2) === 1, 'bloom cost must clamp to 0..1');
assert(refineryBloomResolutionScale(0) === 0 && refineryBloomResolutionScale(0.35) < refineryBloomResolutionScale(1), 'bloom resolution cost must degrade predictably');
assert(refineryBloomStrengthForCost(0.35) < refineryBloomStrengthForCost(1), 'reduced cost must reduce secondary glow strength');
assert(isRefineryBloomAssetLabel('refinery-terminal') && isRefineryBloomAssetLabel('refinery-processor'), 'authored emissives must remain explicit bloom sources');
for (const excluded of ['refinery-floor', 'refinery-bulkhead', 'refinery-crate', 'objective', 'loot', 'hazard', 'interactable', 'enemy']) assert(!isRefineryBloomAssetLabel(excluded), `protected/non-emissive source leaked into bloom selection: ${excluded}`);
const postSource = readFileSync(resolve(process.cwd(), 'src/game/babylonRefineryPostProcessing.ts'), 'utf8');
const browserSmokeSource = readFileSync(resolve(process.cwd(), 'scripts/browser-runtime-smoke.mjs'), 'utf8');
const androidSmokeSource = readFileSync(resolve(process.cwd(), 'scripts/android-runtime-smoke.mjs'), 'utf8');
assert(postSource.includes("new GlowLayer('p27-b12-refinery-selective-bloom'") && postSource.includes('excludeByDefault: true'), 'Babylon refinery bloom must remain selective rather than full-scene');
assert(postSource.includes('this.glow.isEnabled = bloomEnabled') && postSource.includes('this.glow.intensity = budget.bloomStrength') && postSource.includes('this.glow.blurKernelSize = budget.bloomKernelSize'), 'Babylon bloom must follow adaptive cost controls');
assert(postSource.includes("this.canvas.dataset.environmentBloomExcluded = REFINERY_BLOOM_PROFILE.excludedCueGroups.join('+')"), 'Babylon bloom telemetry must publish protected cue groups');
assert(postSource.includes("qaExplicit && this.canvas.dataset.refineryPostStackQa === 'off'"), 'deterministic post-stack disabling must remain QA-only');
assert(postSource.includes('this.glow.dispose()'), 'Babylon glow resources must dispose with the renderer');
assert(browserSmokeSource.includes('BROWSER_P21C_BLOOM_PASS') && androidSmokeSource.includes('ANDROID_P21C_BLOOM_PASS'), 'historical bloom QA coverage must remain wired to the shipped Babylon path');
console.log(`P21C_REFINERY_BLOOM_PASS owner=babylon strength=${REFINERY_BLOOM_PROFILE.strength.toFixed(2)} radius=${REFINERY_BLOOM_PROFILE.radius.toFixed(2)} protected=${REFINERY_BLOOM_PROFILE.excludedCueGroups.join('+')}`);
