import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createRefineryContactDepthAlphaData, REFINERY_CONTACT_DEPTH_PROFILE, refineryContactDepthTelemetry } from '../src/game/refineryContactDepth';
function assert(condition: unknown, message: string) { if (!condition) throw new Error(message); }
assert(REFINERY_CONTACT_DEPTH_PROFILE.opacity > 0 && REFINERY_CONTACT_DEPTH_PROFILE.opacity <= 0.3, 'contact depth opacity must remain restrained');
assert(REFINERY_CONTACT_DEPTH_PROFILE.alphaTextureSize <= 32, 'contact alpha footprint must remain mobile-conscious');
assert(REFINERY_CONTACT_DEPTH_PROFILE.instanceLimit <= 10 && REFINERY_CONTACT_DEPTH_PROFILE.instanceLimit * REFINERY_CONTACT_DEPTH_PROFILE.trianglesPerInstance <= 20, 'contact geometry must remain bounded');
assert(REFINERY_CONTACT_DEPTH_PROFILE.drawCalls === 1, 'contact depth must remain one instanced draw call');
const alpha = createRefineryContactDepthAlphaData(); const size = REFINERY_CONTACT_DEPTH_PROFILE.alphaTextureSize; const alphaAt=(x:number,y:number)=>alpha[(y*size+x)*4+3];
assert(alpha.length === size * size * 4 && alphaAt(Math.floor(size/2), Math.floor(size/2)) > 220 && alphaAt(0,0) === 0, 'contact alpha must be compact, centered, and feathered');
assert(refineryContactDepthTelemetry(10).includes('instances-10:triangles-20:draws-1'), 'contact telemetry must publish bounded scene cost');
const postSource = readFileSync(resolve(process.cwd(), 'src/game/babylonRefineryPostProcessing.ts'), 'utf8');
const browserSmokeSource = readFileSync(resolve(process.cwd(), 'scripts/browser-runtime-smoke.mjs'), 'utf8');
const androidSmokeSource = readFileSync(resolve(process.cwd(), 'scripts/android-runtime-smoke.mjs'), 'utf8');
assert(postSource.includes('RawTexture.CreateRGBATexture') && postSource.includes('REFINERY_CONTACT_DEPTH_PROFILE.instanceLimit') && postSource.includes('this.contactMeshes.forEach((mesh, index) => mesh.setEnabled(index < contactCount))'), 'Babylon contact depth must remain a bounded ground-plane instance pass');
assert(postSource.includes("qaExplicit && this.canvas.dataset.refineryPostStackQa === 'off'"), 'contact-depth QA bypass must be restricted to explicit QA mode');
assert(postSource.includes("this.canvas.dataset.environmentContactDepthProtected = REFINERY_CONTACT_DEPTH_PROFILE.protectedCueGroups.join('+')"), 'contact-depth telemetry must publish protected gameplay groups');
assert(postSource.includes('this.contactTexture.dispose()') && postSource.includes("'environmentContactDepthProtected'"), 'contact-depth resources and telemetry must tear down cleanly');
assert(browserSmokeSource.includes('BROWSER_P21D1_CONTACT_DEPTH_PASS') && androidSmokeSource.includes('ANDROID_P21D1_CONTACT_DEPTH_PASS'), 'contact-depth browser/Android QA must remain present');
console.log(`P21D1_REFINERY_CONTACT_DEPTH_PASS owner=babylon instances=${REFINERY_CONTACT_DEPTH_PROFILE.instanceLimit} protected=${REFINERY_CONTACT_DEPTH_PROFILE.protectedCueGroups.join('+')}`);
