import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { AdaptiveRenderBudget } from '../src/game/renderQuality';
import { spinHabitatRenderProfile } from '../src/game/spinHabitatArchitecture';
import { jovianHarvesterRenderProfile } from '../src/game/jovianHarvesterVisualLanguage';
import { solarYardRenderProfile } from '../src/game/solarYardVisualProfile';
import { perseidRenderProfile } from '../src/game/perseidCapstone';
import { k91RenderProfile } from '../src/game/k91Capstone';
import { orphelineRenderProfile } from '../src/game/orphelineCapstone';
import { hecateRenderProfile } from '../src/game/hecateCapstone';
function assert(condition: unknown, message: string) { if (!condition) throw new Error(message); }
const gameCanvasSource=readFileSync(resolve(process.cwd(),'src/components/GameCanvas.tsx'),'utf8');
const armorySource=readFileSync(resolve(process.cwd(),'src/components/Armory.tsx'),'utf8');
const rendererSource=readFileSync(resolve(process.cwd(),'src/game/babylonCombatRenderer.ts'),'utf8');
const assetsSource=readFileSync(resolve(process.cwd(),'src/game/babylonGraphicsAssets.ts'),'utf8');
const worldSource=readFileSync(resolve(process.cwd(),'src/game/babylonWorldPresentation.ts'),'utf8');
const postSource=readFileSync(resolve(process.cwd(),'src/game/babylonRefineryPostProcessing.ts'),'utf8');
assert(!gameCanvasSource.includes('useRef<SimState>(createMissionState(firstMission))') && gameCanvasSource.includes('useState(() => createMissionState(firstMission))'),'GameCanvas simulation must use lazy one-time initialization');
assert(gameCanvasSource.includes('profileSettingsRef.current.graphicsQuality') && gameCanvasSource.includes('canvas.dataset.graphicsQuality = selectedQuality'),'combat loop must consume/expose graphics quality mode');
assert(armorySource.includes('aria-label="Graphics quality"') && armorySource.includes('<option value="flagship">Flagship</option>') && armorySource.includes('<option value="performance">Performance</option>'),'settings must expose Flagship and Performance');
const desktop=new AdaptiveRenderBudget(false); let snapshot=desktop.sample(16.7,1);
assert(snapshot.tierName==='high' && snapshot.shadowMapSize===1024 && snapshot.vfxDensity===1 && snapshot.transparencyScale===1,'desktop must start at high quality');
assert(snapshot.refineryIblScale===1 && snapshot.refineryBloomScale===1 && snapshot.refineryContactDepthScale===1 && snapshot.refineryAtmosphereScale===1 && snapshot.gameplayCueScale===1,'high tier must retain full secondary and critical cue budgets');
for(let i=0;i<180;i+=1) snapshot=desktop.sample(30,1);
assert(snapshot.tierName==='performance' && !snapshot.shadows && snapshot.shadowMapSize===256 && snapshot.vfxDensity===0.45 && snapshot.transparencyScale===0.4,'sustained slow frames must reach performance tier');
assert(snapshot.refineryIblScale<0.5 && snapshot.refineryBloomScale<0.5 && snapshot.refineryContactDepthScale<0.5 && snapshot.refineryAtmosphereScale<0.5 && snapshot.gameplayCueScale===1,'performance tier must shed secondary effects while preserving critical cues');
for(let i=0;i<700;i+=1) snapshot=desktop.sample(16.4,1); assert(snapshot.tierName==='high','healthy frames must recover desktop quality');
const coarse=new AdaptiveRenderBudget(true); snapshot=coarse.sample(16.7,1); assert(snapshot.tierName==='balanced' && snapshot.shadowMapSize===512 && snapshot.assetCacheEntryBudget===24,'coarse devices must start Balanced');
const flagship=new AdaptiveRenderBudget(true).sample(16.7,1,'flagship'); const perf=new AdaptiveRenderBudget(true).sample(16.7,1,'performance');
assert(flagship.tierName==='high' && perf.tierName==='performance' && flagship.gameplayCueScale===1 && perf.gameplayCueScale===1,'explicit quality modes must alter cost without scaling critical cues');
assert(rendererSource.includes('const budget = this.renderBudget.sample(frameMs, quality, qualityMode)') && rendererSource.includes('budget.vfxDensity') && rendererSource.includes('budget.transparencyScale'),'Babylon renderer must consume adaptive visual budgets');
assert(rendererSource.includes('getBabylonGraphicsAssetRuntime(this.scene).configureBudget({') && rendererSource.includes('dataset.renderMemoryBudget'),'Babylon renderer must apply/expose asset cache budget');
assert(rendererSource.includes('dataset.renderTier = budget.tierName') && rendererSource.includes('dataset.renderFrameMs = budget.smoothedFrameMs.toFixed(2)') && rendererSource.includes('dataset.renderBudget = ['),'Babylon runtime QA must expose tier/frame/budget telemetry');
assert(rendererSource.includes('const drawCalls = this.engine._drawCalls.current') && rendererSource.includes('this.scene.getActiveIndices()'),'Babylon renderer must expose real draw/triangle performance stats');
assert(assetsSource.includes('entry.activeInstances === 0') && assetsSource.includes('maxCachedCompressedBytes') && assetsSource.includes('maxCachedAssets'),'asset cache pressure must evict only idle entries and honor count/byte budgets');
assert(worldSource.includes('quality.materialDepthScale') && worldSource.includes('quality.pickupBeamScale'),'world material/pickup cost must follow adaptive quality');
assert(postSource.includes('renderBudget.refineryBloomScale') && postSource.includes('renderBudget.refineryContactDepthScale') && postSource.includes('renderBudget.refineryAtmosphereScale'),'refinery post stack must consume adaptive secondary-effect scales');
const profiles=[spinHabitatRenderProfile(0.5,true),jovianHarvesterRenderProfile(0.5,true),solarYardRenderProfile(0.5,true),perseidRenderProfile(0.5,true),k91RenderProfile(0.5,true),orphelineRenderProfile(0.5,true),hecateRenderProfile(0.5,true)];
assert(profiles.every(profile=>profile.name==='performance'),'all authored environment/capstone profiles must expose a performance tier');
const worst=new AdaptiveRenderBudget(true); let worstSnapshot=worst.sample(16.7,1); for(let i=0;i<180;i+=1) worstSnapshot=worst.sample(45,1);
assert(worstSnapshot.tierName==='performance' && worstSnapshot.pixelRatioScale<=0.68 && worstSnapshot.detailScale<=0.5 && !worstSnapshot.shadows,'worst-case pressure must reduce raster/detail/shadow cost');
assert(worstSnapshot.gameplayCueScale===1,'worst-case rendering must preserve gameplay-critical information');
console.log('RENDER_PERFORMANCE_PASS owner=babylon sustained=degrade+recover cache=bounded post=adaptive quality-modes=flagship+performance');
