import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { combatAudioBudget, combatAudioVoiceAdmission } from '../src/game/feedback';
import { RUNTIME_SCALABILITY_PROFILES, runtimeAnimationStride, runtimeAssetPreloadReady, runtimePoolTrimTarget } from '../src/game/runtimeScalability';
function assert(condition: unknown, message: string) { if (!condition) throw new Error(message); }
const high=RUNTIME_SCALABILITY_PROFILES.high, balanced=RUNTIME_SCALABILITY_PROFILES.balanced, performance=RUNTIME_SCALABILITY_PROFILES.performance;
assert(high.preloadConcurrency===2 && balanced.preloadConcurrency===1 && performance.preloadConcurrency===1,'mobile/performance preload must serialize while high keeps bounded parallelism');
assert(high.preloadAssetLimit>balanced.preloadAssetLimit && balanced.preloadAssetLimit>performance.preloadAssetLimit,'asset preload residency must shrink under pressure');
assert(!runtimeAssetPreloadReady(3.6,balanced) && runtimeAssetPreloadReady(4.0,balanced),'engine-neutral deferred preload policy must remain bounded');
assert(runtimeAnimationStride({tier:'performance',role:'boss',distance:80,targeted:false,criticalCue:false})===1,'boss animation must never be throttled');
assert(runtimeAnimationStride({tier:'performance',role:'assault',distance:80,targeted:true,criticalCue:false})===1,'targeted enemies must animate every frame');
assert(runtimeAnimationStride({tier:'balanced',role:'assault',distance:80,targeted:false,criticalCue:false})===2,'balanced far enemies should halve authored rig work');
assert(runtimeAnimationStride({tier:'performance',role:'assault',distance:80,targeted:false,criticalCue:false})===3,'performance far enemies should third-rate authored rig work');
assert(runtimePoolTrimTarget(120,8,36)===36 && runtimePoolTrimTarget(42,8,36)===42 && runtimePoolTrimTarget(120,60,36)===60,'pool trimming must be bounded and never remove active visuals');
assert(combatAudioVoiceAdmission(8,2,'tail','background').admitted && !combatAudioVoiceAdmission(combatAudioBudget.backgroundVoiceCeiling,2,'direct','background').admitted,'background audio virtualization must remain pressure-aware');
assert(combatAudioVoiceAdmission(combatAudioBudget.maxVoices,combatAudioBudget.maxTailVoices,'direct','critical').admitted,'critical audio must keep reserved voices');
const rendererSource=readFileSync(resolve(process.cwd(),'src/game/babylonCombatRenderer.ts'),'utf8');
const graphicsSource=readFileSync(resolve(process.cwd(),'src/game/babylonGraphicsAssets.ts'),'utf8');
const canvasSource=readFileSync(resolve(process.cwd(),'src/components/GameCanvas.tsx'),'utf8');
const androidSmokeSource=readFileSync(resolve(process.cwd(),'scripts/android-runtime-smoke.mjs'),'utf8');
assert(rendererSource.includes('runtimeAnimationStride({') && rendererSource.includes('dataset.runtimeAnimationLod'),'Babylon renderer must apply and expose enemy animation LOD');
assert(rendererSource.includes('dataset.runtimePools = [') && rendererSource.includes('runtimeProfile.poolRetention.damageNumbers'),'Babylon renderer must expose bounded runtime-pool pressure');
assert(rendererSource.includes('dataset.assetStreaming = `bounded-preload:') && rendererSource.includes('runtime.preload(selected.map(item => item.spec), preloadConcurrency)'),'Babylon renderer must expose bounded asset streaming');
assert(graphicsSource.includes('async preload(specs: readonly GraphicsAssetSpec[]') && graphicsSource.includes('workerCount'),'Babylon asset runtime must implement bounded-concurrency preload');
assert(graphicsSource.includes('entry.activeInstances === 0') && graphicsSource.includes('maxCachedCompressedBytes'),'Babylon cache eviction must protect mounted instances and honor memory budgets');
assert(canvasSource.includes('feedback.performanceStats()') && canvasSource.includes('dataset.audioVirtualization'),'runtime QA must expose audio virtualization pressure');
assert(androidSmokeSource.includes('runtimeAnimationLod') && androidSmokeSource.includes('runtimePools') && androidSmokeSource.includes('assetStreaming') && androidSmokeSource.includes('audioVirtualization'),'Android smoke must verify Babylon runtime scalability telemetry');
console.log('RUNTIME_SCALABILITY_PASS owner=babylon pools=bounded animation=lod audio=virtualized assets=bounded-preload mechanics=preserved');
