import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

function read(path: string) {
  return readFileSync(resolve(process.cwd(), path), 'utf8');
}
function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

const armory = read('src/components/Armory.tsx');
const combat = read('src/components/GameCanvas.tsx');
const sim = read('src/game/sim.ts');
const meta = read('src/game/meta.ts');
const classSkills = read('src/game/classSkills.ts');
const classSkillFamilyInfluence = meta.match(/function applyClassSkillFamilyInfluence[\s\S]*?\n}\n/)?.[0] ?? '';
const renderer = read('src/game/threeCombatRenderer.ts');
const css = read('src/readability.css');
const shipHub = read('src/components/ShipHub.tsx');
const statsPanel = read('src/components/PlayerStatsPanel.tsx');
const hubVisual = read('src/components/CommandHubVisual.tsx');
const hubCss = read('src/commandHub.css');
const campaignCss = read('src/part11.css');
const menuOverhaulCss = read('src/menuOverhaul.css');
const app = read('src/App.tsx');
const equipmentCss = read('src/equipmentBay.css');
const missionCss = read('src/part4.css');
const objectiveCss = read('src/part7.css');
const rootCss = read('src/index.css');
const mobileCombatCss = read('src/mobileCombatReadability.css');
const qolCss = read('src/qol.css');
const classBuildCss = read('src/classBuilds.css');
const progressionCss = read('src/part3.css');
const classSelect = read('src/components/ClassSelectScreen.tsx');
const classSelectCss = read('src/classSelection.css');
const mobileUiAssets = read('src/game/mobileUiAssets.ts');
const vanguardRushIcon = read('public/assets/ui/skills/vanguard-rush.svg');
const vectorLockIcon = read('public/assets/ui/skills/vector-lock.svg');
const systemsChainIcon = read('public/assets/ui/skills/systems-chain.svg');
const carbineIcon = read('public/assets/ui/weapons/carbine.svg');
const breacherIcon = read('public/assets/ui/weapons/breacher.svg');
const railIcon = read('public/assets/ui/weapons/rail.svg');
const browserSmoke = read('scripts/browser-runtime-smoke.mjs');
const androidSmoke = read('scripts/android-runtime-smoke.mjs');
const androidResumeGate = androidSmoke.match(/if \(resumeOnly\) \{[\s\S]*?process\.exit\(0\);\n\}/)?.[0] ?? '';
const androidSmokeShell = read('scripts/android-runtime-smoke.sh');
const browserWorkflow = read('.github/workflows/browser-e2e.yml');
const androidWorkflow = read('.github/workflows/android-apk.yml');
const parallaxDebt = read('src/game/parallaxDebt.ts');
const scaling = read('src/game/scaling.ts');
const rarity = read('src/game/rarity.ts');
const fieldLoot = read('src/game/fieldLoot.ts');
const feedbackSource = read('src/game/feedback.ts');
const cameraFeedbackSource = read('src/game/combatCameraFeedback.ts');
const lootQuality = read('src/game/lootQuality.ts');
const gearDepth = read('src/game/gearDepth.ts');

assert(shipHub.includes('PARALLAX INTEL // ROUTE RECONSTRUCTION // LV15–18') && shipHub.includes('parallaxDebtNextRequiredLevel'), 'Campaign UI must present the expanded LV15–18 Parallax Debt progression and its level gates.');
assert(shipHub.includes('PARALLAX DEBT // CONTRACT') && shipHub.includes('parallaxChoice.choices.map') && shipHub.includes('chooseParallaxDebtBranch'), 'Contract and campaign surfaces must expose the Parallax Debt decision and closing branch.');
assert(shipHub.includes('PARALLAX INTEL // ROUTE RECONSTRUCTION // LV15–18') && shipHub.includes('parallax-intel-summary') && shipHub.includes('parallax-phase-grid') && shipHub.includes('parallax-route-grid') && shipHub.includes('UNRESOLVED BOUNDARY // DO NOT OVERCLAIM'), 'P1.18 dedicated Parallax Intel dossier is missing phase, route, or evidence-boundary presentation.');
assert(shipHub.includes('parallaxDebtIntel(campaign)') && shipHub.includes('parallaxFindings.length') && shipHub.includes('CLASSIFIED UNTIL FALSE HORIZON'), 'Parallax Intel presentation is not synchronized to campaign evidence and route reveal state.');
assert(campaignCss.includes('P1.18 // PARALLAX DEBT INTEL DOSSIER') && campaignCss.includes('.parallax-phase-grid') && campaignCss.includes('.parallax-bank-grid') && campaignCss.includes('@media (orientation:landscape) and (max-height:650px)'), 'Parallax Intel dossier is missing responsive/mobile-landscape presentation coverage.');
assert(app.includes('getParallaxDebtContract(campaign, profile.level)'), 'Contract generation must enforce Parallax Debt operator-level gates.');
assert(parallaxDebt.includes("authoredContracts: 12") && parallaxDebt.includes("id: 'expose-route'") && parallaxDebt.includes("id: 'hold-route'") && parallaxDebt.includes('Common Reference') && parallaxDebt.includes('Private Vector'), 'Parallax Debt content must preserve the nine-mission spine and author both final three-operation branches.');
assert(scaling.includes("contract.campaignChapter === 'parallax-debt'") && scaling.includes("8 + Math.floor((contract.campaignStep ?? 0) / 3)"), 'Parallax Debt must retain late-game tier scaling across its LV15–18 phases.');

assert(meta.includes("name: 'Void Ram'") && meta.includes("name: 'Breach Cascade'") && meta.includes("name: 'Counterfort'"), 'Vanguard capstone interaction definitions are incomplete.');
assert(meta.includes("name: 'Inertial Dividend'") && meta.includes("name: 'Reference Solution'") && meta.includes("name: 'Redline Needle'"), 'Vector same-class capstone interaction definitions are incomplete.');
assert(meta.includes("name: 'Induction Sink'") && meta.includes("name: 'Recursive Bus'") && meta.includes("name: 'Mesh Reflux'"), 'Systems capstone interaction definitions are incomplete.');
assert(meta.includes('vectorCapstoneInteractionFor') && meta.includes("capstone ? \` // \${capstone.name}\` : ''"), 'P5.9 build identity should surface the active LV16 capstone doctrine.');
assert(meta.includes("name: 'Pressure Recirculator'") && meta.includes("name: 'Breach Stack'") && meta.includes("name: 'Counterfort Bracing'") && meta.includes("name: 'Reaction Ledger'") && meta.includes("name: 'Survey Ballistics'") && meta.includes("name: 'Thermal Slip'") && meta.includes("name: 'Mesh Orchestra'") && meta.includes("name: 'Bus Harmonics'") && meta.includes("name: 'Heat Exchange'"), 'P5.10 specialization gear-link definitions are incomplete.');
assert(meta.includes('specializationGearSynergyForProfile') && meta.includes("gearSynergy?.active ? \` // \${gearSynergy.definition.name}\` : ''"), 'P5.10 active gear links should participate in build identity.');
assert(meta.includes('preferredTags:') && meta.includes('minimumTagMatches: 2') && meta.includes('itemMatchesSpecializationGearDefinition'), 'P8.5-G specialization gear links must be tag/threshold driven.');
assert(!meta.includes('requiredAffix:'), 'P8.5-G should not retain ordinary exact-affix specialization gates.');
assert(armory.includes('Tag threshold met on this frame.') && armory.includes('MATCHED FRAME'), 'Equipment UI should explain tag-routed specialization gear links.');
assert(armory.includes('SPECIALIZATION GEAR LINK') && armory.includes('GEAR LINK //') && armory.includes('itemMatchesSpecializationGearSynergy'), 'Equipment and specialization UI must surface P5.10 gear-link activation and candidate frames.');
assert(statsPanel.includes('specializationGearSynergyForProfile') && statsPanel.includes('GEAR LINK ${activeGearSynergy.definition.name}'), 'Build Stats does not surface active P5.10 specialization gear links.');
assert(meta.includes("name: 'Thermal Shunter'") && meta.includes("specializationIds: ['grid-weaver', 'capacitor-conductor', 'thermal-shunter']") && sim.includes('systemsCrossfeed') && sim.includes('THERMAL CROSSFIRE'), 'P5.6 Systems third specialization is missing from class metadata or combat feedback.');
assert(statsPanel.includes('capstoneInteractionFor') && statsPanel.includes('CAPSTONE ${activeCapstone.name}'), 'Build Stats does not surface active class capstone interactions.');
assert(armory.includes('availableSpecializations.map'), 'Operator Network UI must render every class specialization from shared metadata.');
assert(armory.includes('Search Operator Network') && armory.includes('BEFORE / AFTER BUILD MATH') && armory.includes('networkPlanTargets') && armory.includes('operatorNetworkPlan'), 'P9-E planner UI must expose search, persistent in-session plan state, aggregate pathing, and before/after build math.');
assert(armory.includes('handleNetworkNavigation') && armory.includes("event.key === 'ArrowRight'") && armory.includes('navigator.getGamepads()') && armory.includes('buttons[15]'), 'P9-E progression navigation must support keyboard/controller directional input in addition to touch.');
assert(progressionCss.includes('P9-E // Operator Network planner') && progressionCss.includes('.network-branch button.planned') && progressionCss.includes('@media (max-width: 900px)'), 'P9-E planner presentation is missing planned-route cues or mobile responsive controls.');
assert(armory.includes('P9-F // RECALIBRATION') && armory.includes('runNetworkRefund') && armory.includes('runNetworkRebuild') && armory.includes('operatorNetworkRespecCreditCost'), 'P9-F progression UI must expose safe node refunds, full rebuilds, and visible recalibration costs.');
assert(armory.includes('P10-A // CRAFTING CONTRACT') && armory.includes('craftingRulesForItem') && armory.includes('LEGAL POOL') && armory.includes('Base frame + class-family ownership decide this list.'), 'P10-A/P10-D Crafting UI must expose the canonical rule contract and visible base/class-owned legal pools.');
assert(classBuildCss.includes('P10-A // Crafting rules foundation') && classBuildCss.includes('.crafting-rules-contract') && classBuildCss.includes('.crafting-pool-entry.legal'), 'P10-A Crafting presentation is missing legal/locked pool readability.');
assert(progressionCss.includes('P9-F // Operator Network recalibration') && progressionCss.includes('.network-recalibration') && progressionCss.includes('.network-recalibration-actions'), 'P9-F recalibration presentation is missing responsive mobile controls.');
assert(armory.includes('CAPSTONE LINK //') && armory.includes('capstoneInteractionFor'), 'Build Skills UI does not surface active specialization/evolution capstone links.');
assert(!armory.includes('Review faction doctrines'), 'Equipment Bay still advertises undiscovered faction doctrine targets.');
assert(!armory.includes('2 PIECE'), 'Equipment Bay still exposes 2-piece set targets.');
assert(!armory.includes('4 PIECE'), 'Equipment Bay still exposes 4-piece set targets.');
assert(!armory.includes('setName'), 'Equipment Bay still renders undiscovered set names.');
assert(armory.includes('PRIMARY EFFECT'), 'Item inspector is missing plain-language quick read.');
assert(rarity.includes("cue: 'RULE-CHANGER'") && armory.includes('rarityDisplayLabel(rarity)'), 'Rarity meaning cues are missing from the shared contract or gear UI.');
assert(rarity.includes("export const rarityOrder = ['Field', 'Refined', 'Prototype', 'Singular'] as const") && rarity.includes('accessibleLabel') && rarity.includes('colorValue') && rarity.includes('shape:') && rarity.includes('icon:'), 'P7-A rarity contract is missing order, color, icon, shape, or accessible-text tokens.');
assert(armory.includes('rarity-contract-legend') && armory.includes('Equipment rarity guide') && armory.includes('function RarityText') && armory.includes('definition.icon'), 'Build gear UI is not exposing the shared non-color rarity language.');
assert(equipmentCss.includes('P7-A // shared rarity contract presentation') && equipmentCss.includes('.rarity-contract-legend') && equipmentCss.includes('.rarity-shape'), 'Rarity legend presentation is missing responsive shape-cue styling.');
assert(fieldLoot.includes('const definition = rarityDefinition(rarity)') && fieldLoot.includes('color: definition.colorValue') && fieldLoot.includes('label: definition.worldLabel'), 'Ground loot presentation is not sourced from the shared rarity contract.');
assert(meta.includes('export type Rarity = ItemRarity') && lootQuality.includes("Exclude<ItemRarity, 'Singular'>") && gearDepth.includes('export type GearRarity = ItemRarity'), 'Equipment systems still duplicate the rarity type contract.');
assert(armory.includes('activeDoctrineStates'), 'Discovered-only loadout interactions are missing.');

assert(combat.includes('HEALTH EXPOSED'), 'Combat UI does not explicitly call out broken armor and exposed health.');
assert(combat.includes('data-target-id={focusEnemy.id}') && combat.includes('Assisted target locked: ${focusEnemy.label}') && combat.includes('<small>ASSIST LOCK</small>'), 'Assisted hostile health readout is missing or disconnected from the retained target.');
assert(combat.includes('className="combat-sr-status"') && combat.includes('aria-live="polite"') && css.includes('.combat-sr-status') && css.includes('@media (prefers-reduced-motion: reduce)'), 'P8-C target lock accessibility or reduced-motion presentation is missing.');
assert(css.includes('rgba(167,238,215,.68)') && css.includes('inset 3px 0 0 rgba(167,238,215,.7)'), 'P8-C target readout lacks its high-contrast assisted-lock treatment.');
assert(combat.includes('DROP ON DECK'), 'Ground-loot explanation is missing from combat HUD.');
assert(combat.includes('ctx.fillText(presentation.label'), 'High-value ground loot does not receive a readable world label.');
assert(fieldLoot.includes('groundLootPresentation') && fieldLoot.includes("pickupCue: definition.rank >= 2 ? 'rareLoot' : 'loot'"), 'P7-B world loot is missing shared beacon scaling or rarity-aware pickup feedback.');
assert(combat.includes('drawGroundLootShape') && combat.includes('nearbyLootRange') && combat.includes('nearbyLootDirection') && combat.includes('feedback.cue(groundLootPresentation(latestLoot.rarity).pickupCue)'), 'P7-B combat presentation is missing rarity-shaped markers, distance guidance, or pickup audio.');
assert(renderer.includes('groundLootMarkerGeometries') && renderer.includes('visual.marker.geometry = this.groundLootMarkerGeometries[presentation.shape]') && renderer.includes('visual.beam.scale.y = presentation.beaconScale'), 'P7-B Three.js loot markers do not preserve non-color rarity shapes and beacon hierarchy.');
assert(feedbackSource.includes("cue === 'rareLoot' ? [8, 18, 12]") && feedbackSource.includes("cue === 'loot' ? 5") && feedbackSource.includes('navigator.vibrate(scaledVibration)') && feedbackSource.includes("this.settings.effectIntensity === 'reduced' ? .55 : 1"), 'P7-B pickup feedback is missing distinct rarity-aware or accessibility-scaled haptic treatment.');
assert(rarity.includes('export function rarityDisplayLabel') && rarity.includes("${rarity.toUpperCase()} · ${definition.cue}"), 'P7-C is missing the shared menu/feed rarity label formatter.');
assert(armory.includes('function RarityText') && armory.includes('rarityDisplayLabel(rarity)') && armory.includes('<RarityText rarity={equipped.rarity} />') && armory.includes('<RarityText rarity={selected.rarity} />') && !armory.includes('rarityCue(item)'), 'P7-C Build surfaces are not consistently using the shared rarity label.');
assert(app.includes('rarityDisplayLabel(item.rarity)') && app.includes('rarityDefinition(item.rarity).icon') && !app.includes('debriefRarityCue'), 'P7-C debrief still owns duplicate rarity wording or lacks the shared non-color cue.');
assert(fieldLoot.includes('lootFeedLabel') && fieldLoot.includes('return rarityDisplayLabel(rarity)') && sim.includes('lootFeedLabel(drop.rarity)') && !sim.includes('lootLabel(drop.rarity)'), 'P7-C combat pickup feed is not routed through shared menu rarity language.');
assert(shipHub.includes('Equipment reward rarity language') && shipHub.includes('rarityOrder.map') && shipHub.includes("rarityDisplayLabel('Singular')"), 'P7-C reward previews are missing shared rarity language.');
assert(equipmentCss.includes('--gear-rarity:#69aee8') && equipmentCss.includes('--gear-rarity:#c47ce8') && equipmentCss.includes('--gear-rarity:#f0a45b'), 'P7-C Build rarity palette drifted from the shared rarity contract.');
assert(css.includes('.recovery-review-card.rarity-refined { --gear-rarity:#69aee8') && css.includes('.recovery-review-card.rarity-prototype { --gear-rarity:#c47ce8') && css.includes('.recovery-review-card.rarity-singular { --gear-rarity:#f0a45b'), 'P7-C debrief rarity palette drifted from the shared rarity contract.');
assert(missionCss.includes('.reward-rarity-guide') && missionCss.includes('grid-template-columns: repeat(2,minmax(0,1fr))'), 'P7-C reward rarity guide is missing responsive presentation.');
assert(armory.includes('gear-identity-grid') && armory.includes('Equipment identity and compatibility') && armory.includes('<small>BASE</small>') && armory.includes('<small>FRAME</small>') && armory.includes('<small>RECOVERY</small>') && armory.includes('<small>FRAME QUALITY</small>') && armory.includes('<small>MODIFIERS</small>') && armory.includes('<small>AUGMENTS</small>') && armory.includes('<small>SOURCE</small>') && armory.includes('<small>COMPATIBILITY</small>'), 'P7-D inspector is missing required identity, quality, recovery, modifier, augment, source, or compatibility telemetry.');
assert(armory.includes('build-change-panel') && armory.includes('BUILD-CHANGING EFFECTS') && armory.includes('isBuildChangingItem') && armory.includes('MECHANICAL MOD // G') && armory.includes('SINGULAR SIGNATURE'), 'P7-D inspector is missing explicit build-changing effect detection/presentation.');
assert(armory.includes("type RarityFilter = 'all' | ItemRarity") && armory.includes("gearFilter === 'class-fit'") && armory.includes("gearFilter === 'augmented'") && armory.includes("gearFilter === 'build-changing'") && armory.includes("gearSort === 'rarity'") && armory.includes("gearSort === 'modifier'") && armory.includes("gearSort === 'augments'"), 'P7-D storage tools are missing rarity/class/augment/build filters or inspector-driven sorts.');
assert(armory.includes('item.baseId') && armory.includes("item.recoverySource ?? ''") && armory.includes('augment.hardware') && armory.includes('highestModifierGrade(item)'), 'P7-D storage search/cards do not expose base, source, augment, recovery, or modifier-grade metadata.');
assert(equipmentCss.includes('.gear-identity-grid') && equipmentCss.includes('.build-change-panel') && equipmentCss.includes('.gear-identity-grid .compatible') && equipmentCss.includes('.gear-identity-grid .locked'), 'P7-D inspector telemetry is missing responsive compatibility/build-change styling.');
assert(qolCss.includes('grid-template-columns: minmax(190px, 1fr) 150px 180px auto'), 'P7-D expanded inventory controls are not laid out for search + rarity + sort + reset.');
assert(armory.includes('singularSurfaceRule') && armory.includes('singular-hero') && armory.includes('singular-surface-callout') && armory.includes('singular-rule-preview') && armory.includes('FIXED RULE //'), 'P7-E Singular treatment is missing from loadout, storage, inspector, or crafting surfaces.');
assert(app.includes('singular-debrief-rule') && app.includes('✦ FIXED SINGULAR RULE'), 'P7-E mission debrief is not surfacing the Singular fixed rule directly.');
assert(combat.includes('loot-radar-signature') && combat.includes('rarity-${nearbyLoot.rarity.toLowerCase()}') && combat.includes('FIXED RULE REVEALS ON PICKUP'), 'P7-E world Singular recovery treatment is missing from the touch HUD.');
assert(shipHub.includes('premium-rarity-guide') && shipHub.includes('<strong>FIXED RULE</strong>') && missionCss.includes('.premium-rarity-guide'), 'P7-E contract reward guidance is missing premium Singular language.');
assert(equipmentCss.includes('.singular-hero') && equipmentCss.includes('.singular-surface-callout') && equipmentCss.includes('.inventory-card .singular-rule-preview') && css.includes('.loot-radar.rarity-singular') && css.includes('.singular-debrief-rule'), 'P7-E premium Singular styling is incomplete across item surfaces.');
assert(!armory.includes('title=') && !app.includes('title='), 'P7-E item information must remain tap-visible and cannot depend on hover-only title data.');
assert(css.includes('P7-B // world-loot distance + non-color rarity readability') && css.includes('.loot-radar-shape') && css.includes('.loot-radar-meta') && css.includes('.loot-radar-instruction'), 'P7-B loot radar styling is missing mobile-safe shape or distance readability.');
assert(renderer.includes("enemy.role === 'elite' ? 2.2 : 1.9"), 'Three.js hostile bars are still too small for mobile readability.');
assert(renderer.includes('0xff725f') && renderer.includes('0x8ee8ff') && renderer.includes('THREE.AdditiveBlending') && renderer.includes('toneMapped: false'), 'Three.js hostile bars are not using the bright mobile treatment.');
assert(css.includes('.target-readout') && css.includes('.gear-quick-read') && css.includes('.loot-radar'), 'Readability stylesheet is incomplete.');
assert(armory.includes('gear-deep-details') && css.includes('.gear-deep-details'), 'Gear inspector does not separate essential comparison from advanced telemetry.');
assert(equipmentCss.includes('gear-layout.has-selection::before') && equipmentCss.includes('width: min(72vw, 760px)'), 'Landscape mobile gear inspector is missing focused modal treatment.');
assert(equipmentCss.includes('.item-inspector .sheet-close') && equipmentCss.includes('@media (pointer: coarse)'), 'Gear inspector cannot be reliably closed on coarse-pointer landscape devices.');
assert(equipmentCss.includes('MOBILE INSPECTOR SCROLL RELIABILITY') && equipmentCss.includes('touch-action: pan-y') && equipmentCss.includes('-webkit-overflow-scrolling: touch') && equipmentCss.includes('height: calc(100dvh'), 'Mobile gear inspector is not a bounded touch-scroll surface.');
assert(armory.includes('inspector-header') && armory.includes('inspector-scroll') && armory.includes('gear-summary-grid') && armory.includes('impact-stat'), 'Item inspector redesign hierarchy is missing.');
assert(equipmentCss.includes('ITEM INSPECTOR REDESIGN') && equipmentCss.includes('grid-template-rows: auto minmax(0, 1fr) auto') && equipmentCss.includes('.inspector-scroll') && equipmentCss.includes('overflow: hidden'), 'Item inspector is not using the fixed-header/scroll-body/action-dock layout.');
assert(equipmentCss.includes('ITEM INSPECTOR LAZY-CSS CASCADE GUARD') && equipmentCss.includes('.gear-layout .item-inspector.open'), 'Lazy Armory CSS can override the redesigned inspector grid.');
assert(armory.includes("useState<string | null>(null)") && armory.includes("newLootIds.length > 0 ? 'new' : 'all'") && armory.includes('item-inspector-backdrop'), 'Recovered loot should open as a dismissible filtered list rather than trapping the player in an inspector.');
assert(equipmentCss.includes('MOBILE INSPECTOR ESCAPE RELIABILITY') && equipmentCss.includes('.item-inspector-backdrop') && equipmentCss.includes('pointer-events: none'), 'Mobile item inspector backdrop/escape behavior is missing.');
assert(css.includes('DEBRIEF RARITY COLORS') && css.includes('.recovery-review-card.rarity-singular') && css.includes('.recovery-review-card.rarity-prototype'), 'Debrief recovery cards are missing rarity color treatment.');
assert(objectiveCss.includes('MOBILE OBJECTIVE COMPACTNESS OVERRIDE') && objectiveCss.includes('width: min(300px, 34vw)') && objectiveCss.includes('.post-clear-objective small { display: none; }'), 'Post-clear objective guidance can still cover too much of the mobile combat view.');
assert(missionCss.includes('RESPONSIVE MISSION SURFACE RELIABILITY') && missionCss.includes('overflow-y: auto'), 'Combat completion overlays can still extend outside the visible viewport.');
assert(missionCss.includes('place-items: start center') && missionCss.includes('height: 100dvh'), 'Mission debrief can still center oversized content outside the scrollable viewport.');
assert(missionCss.includes('max-height: 900px'), 'Short landscape viewport scaling regression coverage is missing.');
assert(app.includes('RECOVERED EQUIPMENT // REVIEW') && app.includes('Confirm discard'), 'Mission debrief is missing acquired-gear review/discard controls.');
assert(app.includes('discardRecoveredItem') && app.includes('discardItem(current, itemId)'), 'Debrief discard is not wired to persistent profile inventory.');
assert(app.includes('debriefRunSequenceRef') && app.includes('current?.runId === debriefRunId'), 'Telemetry completion can still mutate a later mission debrief.');
assert(app.includes('LOCAL SAVE FAILED') && app.includes('!saveGameState(profile, campaign)') && app.includes("current === persistenceWarning ? '' : current") && shipHub.includes("const displayedStatusMessage = statusMessage ||") && shipHub.includes("role={statusMessage ? 'alert' : 'status'}"), 'Local persistence failures are not surfaced reliably to an already-mounted ShipHub.');
assert(shipHub.includes('traceRequestIdRef') && shipHub.includes('const requestId = ++traceRequestIdRef.current') && shipHub.includes('traceRequestIdRef.current !== requestId'), 'Operations trace loading can still let an older request overwrite a newer selection.');
assert(!shipHub.includes('bossSingularNames'), 'Contract Board still imports unrecovered boss gear names.');
assert(!shipHub.includes('locationSingularNames'), 'Contract Board still imports unrecovered location gear names.');
assert(!shipHub.includes('factionEquipmentNames'), 'Ship UI still exposes unrecovered faction gear names.');
assert(!shipHub.includes('DEDICATED SINGULAR POOL'), 'Contract Board still advertises a named Singular pool.');
assert(!shipHub.includes('LOCATION CHASE POOL'), 'Contract Board still advertises location chase gear before discovery.');
assert(!shipHub.includes('RECOVERY CEILING // RL'), 'Contract Board still leads with opaque recovery-level jargon.');
assert(shipHub.includes('EQUIPMENT RECOVERY'), 'Contract Board is missing the discovery-safe equipment explanation.');
assert(shipHub.includes('Frame identities and interactions reveal only after recovery.'), 'Faction panel is missing acquisition-first discovery guidance.');
assert(shipHub.includes("useState<Tab>('overview')"), 'App does not open on the new command overview.');
assert(shipHub.includes("switchTab('stats')"), 'Command hub is missing Player Stats navigation.');
assert(shipHub.includes('CommandHubVisual'), 'Command hub visual is not integrated.');
assert(shipHub.includes('PlayerStatsPanel'), 'Player stats page is not integrated.');
assert(statsPanel.includes('Current build') && statsPanel.includes('Vacuum resistance') && statsPanel.includes('BURST DPS'), 'Player stats page is missing explained final stats.');
assert(statsPanel.includes('createSimulation(build)'), 'Stats page is not using the real combat build for final values.');
assert(hubVisual.includes('command-bridge-schematic') && hubVisual.includes('OPERATOR LV') && hubVisual.includes('GEAR LINK'), 'Opening hub does not visually represent the ship and operator readiness.');
assert(hubVisual.includes('COMMAND READY') && hubVisual.includes('bridge-compact-readiness') && !hubVisual.includes('bridge-gear-panel') && !hubVisual.includes('bridge-gear-strip'), 'Opening Command surface is not using the compact readiness treatment.');
assert(hubCss.includes('.command-overview') && hubCss.includes('.player-stat-grid'), 'Command hub responsive styling is incomplete.');
assert(shipHub.includes("type PrimaryArea = 'command' | 'operations' | 'operator' | 'ship' | 'intel'"), 'Ship Hub has not collapsed navigation into five primary mental models.');
assert(shipHub.includes('command-rail-nav') && shipHub.includes('section-tabs') && shipHub.includes('areaTabs'), 'Tactical Command Deck navigation shell is incomplete.');
assert(!shipHub.includes('aria-label="Ship areas"'), 'Legacy nine-tab primary navigation is still rendered.');
assert(menuOverhaulCss.includes('.command-rail') && menuOverhaulCss.includes('.tactical-workspace') && menuOverhaulCss.includes('.command-bridge') && menuOverhaulCss.includes('max-height: 650px') && menuOverhaulCss.includes('max-height: 380px') && menuOverhaulCss.includes('.ship-hub.area-command .hub-resource-ribbon'), 'Tactical Command Deck responsive visual system is incomplete at standard or ultra-short landscape heights.');
assert(menuOverhaulCss.includes('prefers-reduced-motion') && menuOverhaulCss.includes('safe-area-inset-bottom'), 'Menu overhaul is missing reduced-motion or safe-area handling.');
assert(shipHub.includes("operations: ['contracts', 'operations']") && shipHub.includes("intel: ['campaign', 'stories', 'factions']") && shipHub.includes("stats: 'Stats'") && shipHub.includes("operations: 'Uplink'"), 'Primary information architecture still mixes campaign/intel with deployment or uses ambiguous Stats/Uplink labels.');
assert(!shipHub.includes('<button className="hub-build-button" onClick={onOpenBuild}>Equipment</button>') && !shipHub.includes('<b>Tune loadout</b>') && shipHub.includes('command-priority-panel'), 'Command overview still duplicates Build navigation or lacks contextual priorities.');
assert(armory.includes("gear: 'Loadout'") && armory.includes("reconstruct: 'Crafting'") && armory.includes("network: 'Progression'") && armory.includes("protocols: 'Skills'"), 'Build tabs still expose implementation terminology instead of player-facing labels.');
assert(menuOverhaulCss.includes('UI SIMPLIFICATION // PRIORITY-FIRST COMMAND + CONTRACT CARDS') && mobileCombatCss.includes('MOBILE HUD INFORMATION BUDGET'), 'UI simplification styling is missing command/contract or mobile-HUD coverage.');
assert(shipHub.includes("overview: 'Overview'") && shipHub.includes("const pageTitle = tab === 'overview' ? 'Overview'"), 'Command overview still repeats Command/Tasking language instead of using a neutral overview page title.');
assert(combat.includes('visibleConsumables') && combat.includes("consumableDefinitions.filter(item => consumableStock[item.id] > 0)") && mobileCombatCss.includes('max-width: min(360px, 30vw)'), 'Mobile combat still reserves persistent HUD space for empty consumables or oversized mission alerts.');
assert(browserSmoke.includes("keyboardActivateButton('Operations')") && browserSmoke.includes("keyboardActivateButton('Contracts')"), 'Browser E2E does not follow the new Command > Operations > Contracts hierarchy.');
assert(browserSmoke.includes('BROWSER_MOBILE_MENU_PASS') && browserSmoke.includes('primaryCount !== 5'), 'Browser E2E is missing mobile Tactical Command rail layout coverage.');
assert(armory.includes("import '../menuOverhaul.css';"), 'Equipment surface is not using the Tactical Command visual system.');
assert(!shipHub.includes('No urgent ship tasks'), 'Empty priority chrome is still rendered when nothing needs attention.');
assert(!shipHub.includes('command-nav-grid'), 'Overview still duplicates the full tab navigation.');
assert((statsPanel.match(/Weapon stat glossary/g) ?? []).length === 1, 'Weapon stat help should be shared once, not repeated per weapon.');
assert(!statsPanel.includes('What these numbers mean'), 'Per-weapon duplicate glossary remains.');
assert(armory.includes('compact-discovery') && !armory.includes('Build changes save automatically on this device.'), 'Equipment Bay still shows repetitive instructional/status chrome.');
assert(combat.includes('mission-build-label') && !combat.includes('objective-progress-chip') && combat.includes("const focusEnemy = hud.bossActive ? null : lockedHostile") && combat.includes("(!coarse || hud.classActive)"), 'Combat HUD still duplicates objective guidance or permanently renders secondary target/class panels.');
assert(combat.includes('hostileRouteMode') && combat.includes('objectiveRouteMode'), 'Combat cleanup guidance is missing obstacle-aware route state.');
const gameRootRule = rootCss.match(/\.game-root\s*\{[^}]*\}/)?.[0] ?? '';
const gameCanvasRule = rootCss.match(/\.game-canvas\s*\{[^}]*\}/)?.[0] ?? '';
const touchStickRule = rootCss.match(/\.touch-stick\s*\{[^}]*\}/)?.[0] ?? '';
const touchButtonRule = rootCss.match(/\.touch-button\s*\{[^}]*\}/)?.[0] ?? '';
const overlayRule = rootCss.match(/\.overlay\s*\{[^}]*\}/)?.[0] ?? '';
const overlayCardRule = rootCss.match(/\.overlay-card\s*\{[^}]*\}/)?.[0] ?? '';
assert(!combat.includes("document.addEventListener('touchmove'") && !combat.includes("document.addEventListener('gesturestart'"), 'Combat still suppresses touch gestures at document scope.');
assert(!gameRootRule.includes('touch-action: none'), 'Combat root still disables gestures for descendant overlays.');
assert(gameCanvasRule.includes('touch-action: none') && touchStickRule.includes('touch-action: none') && touchButtonRule.includes('touch-action: manipulation'), 'Combat input surfaces are missing scoped touch-action protection.');
assert(overlayRule.includes('touch-action: pan-y') && overlayRule.includes('overflow-y: auto') && overlayCardRule.includes('touch-action: pan-y') && overlayCardRule.includes('overflow-y: auto'), 'Combat overlays are not explicit vertical touch-scroll surfaces.');
assert(shipHub.includes('OPERATOR READINESS') && shipHub.includes('readiness-chip'), 'Contract board is missing visible operator/monster readiness guidance.');
assert(shipHub.includes("type ContractSort = 'level-match'") && shipHub.includes('aria-label="Search contracts"') && shipHub.includes('contract-card-readiness') && !shipHub.includes('contract-quick-deploy') && shipHub.includes("filter === 'ready'"), 'Contract Board QoL search, level-match sorting, ready filtering, or simplified card hierarchy is missing.');
assert(armory.includes("type InventoryFilter = 'all' | 'new' | 'usable'") && armory.includes('Clear storage filters') && armory.includes('Usable now') && armory.includes("window.addEventListener('keydown', closeInspector)"), 'Equipment storage QoL filtering, reset, or Escape-to-close behavior is missing.');
assert(armory.includes('OPERATOR CLASS // FIELD DOCTRINE') && armory.includes('class-resonance-strip') && armory.includes('availableSpecializations') && armory.includes('class-freedom-note'), 'Operator class selection, class-specific specialization routes, or open-build guidance is missing.');
assert(armory.includes('CLASS RESONANCE') && armory.includes('itemBuildAffinities(item)') && armory.includes('class-resonance-pill'), 'Equipment UI does not surface class resonance on recovered gear.');
assert(classBuildCss.includes('.operator-class-grid') && classBuildCss.includes('.class-resonance-strip') && classBuildCss.includes('.gear-class-fit') && classBuildCss.includes('max-height: 650px'), 'Operator class/build styling is incomplete or missing mobile-landscape coverage.');
assert(statsPanel.includes('build-class-summary') && statsPanel.includes('gearResonanceForProfile'), 'Player Stats does not expose the active class and gear resonance state.');
assert(app.includes("type Screen = 'class'") && app.includes("initialGameState.profile.classSelectionComplete ? 'ship' : 'class'") && app.includes('ClassSelectScreen'), 'Fresh profiles are not routed through a dedicated class selection screen.');
assert(classSelect.includes('Pick your combat role') && classSelect.includes('One weapon family per class') && classSelect.includes('Choose the role that sounds fun') && classSelect.includes('Select ${definition.name} class') && classSelect.includes('aria-label={`Confirm ${selected.name}`}') && classSelect.includes('Play {selected.name}'), 'Class intake is missing beginner-first role selection, arsenal ownership guidance, or confirmation controls.');
assert(classSelect.includes('classIntakeCopy') && classSelect.includes('HOW TO PLAY') && classSelect.includes('YOUR FIRST 3 ABILITIES') && classSelect.includes('Build details for later') && classSelect.includes('operatorClassOnboardingRecovery') && classSelect.includes('classAbilityKits'), 'Class intake does not lead with plain-language playstyle, starting abilities, or progressive disclosure for advanced build details.');
assert(meta.includes('export function isItemClassCompatible') && meta.includes('recoverySlotOrderForProfile') && meta.includes('activeWeaponFamilyForProfile(profile), ...universalRecoverySlotOrder') && meta.includes("slot: 'rail', name: 'Needleline Survey Rails'") && meta.includes("slot: 'carbine', name: 'Relay M-7 Driver'") && meta.includes('.filter(item => isEquipmentSlotClassCompatible(profile, item.slot))'), 'P8-E loot generation is not enforcing class-owned weapon recovery across ordinary and premium drops.');
assert(armory.includes('Weapon family ownership tutorial') && armory.includes('New combat recoveries roll only your owned weapon family') && armory.includes('weaponFamilyLessons') && armory.includes('Class-locked armament') && armory.includes("!isItemClassCompatible(profile, item)") && armory.includes('Vanguard owns Breacher, Vector owns Rail Lance, and Systems owns Carbine') && !armory.includes('Usable by ${activeClass.name}; no class lock.') && !armory.includes('Every progression branch, weapon family, and Skill Lens remains available'), 'P8-E Build UI does not teach and enforce arsenal ownership consistently.');
assert(shipHub.includes('activeWeaponFamilyForProfile(profile)') && shipHub.includes('directiveSingularNames(selected.directiveTier, profile)') && shipHub.includes('Weapon recoveries are filtered to your {ownedWeaponLabel} arsenal') && shipHub.includes('Combat Suit, Systems Rig, and Implant remain universal support slots'), 'P8-E contract reward preview does not explain or filter class-owned weapon outcomes.');
assert(mobileUiAssets.includes('/assets/ui/classes/vanguard.svg') && mobileUiAssets.includes('/assets/ui/classes/vector.svg') && mobileUiAssets.includes('/assets/ui/classes/systems.svg'), 'Mobile UI asset catalog is missing lightweight authored class crests.');
assert(mobileUiAssets.includes('vanguard-rush.svg') && mobileUiAssets.includes('vector-lock.svg') && mobileUiAssets.includes('systems-chain.svg') && mobileUiAssets.includes('weaponIconAssets'), 'Mobile UI asset catalog is missing class-skill or weapon icon mappings.');
assert(classSelect.includes('classSkillIconAssets') && classSelect.includes('operatorClassIconAssets') && classSelect.includes('class-skill-key'), 'Class intake is not using the mobile icon asset catalog.');
assert(combat.includes('classSkillIconAssets') && combat.includes('operatorClassIconAssets') && combat.includes('class-mechanic-hud') && !combat.includes('desktop-weapons') && !combat.includes('weapon-cycle'), 'Combat HUD is missing class/skill icon integration or still exposes cross-family weapon swap controls.');
assert([vanguardRushIcon, vectorLockIcon, systemsChainIcon, carbineIcon, breacherIcon, railIcon].every(icon => icon.includes('<svg') && icon.includes('viewBox=')), 'One or more mobile SVG combat assets are malformed.');
assert(classSelectCss.includes('.class-choice-grid') && classSelectCss.includes('.class-selected-panel') && classSelectCss.includes('.class-starting-kit-grid') && classSelectCss.includes('.class-card-kit img') && classSelectCss.includes('.class-skill-key img') && classSelectCss.includes('.class-advanced-details') && classSelectCss.includes('.class-mechanic-hud') && classSelectCss.includes('.game-root.class-vanguard') && classSelectCss.includes('.game-root.class-vector') && classSelectCss.includes('.game-root.class-systems') && classSelectCss.includes('max-height: 650px') && classSelectCss.includes('safe-area-inset-left'), 'Class intake/skill-kit/combat feedback styling is missing progressive disclosure, class theming, landscape, or safe-area coverage.');
assert(combat.includes('getClassMechanicStatus') && combat.includes('class-mechanic-hud') && combat.includes('Class signature status'), 'Combat HUD is missing live class signature feedback.');
assert(combat.includes('getAbilityKit') && combat.includes('abilityKit.map') && !combat.includes('abilityMeta.map'), 'Combat controls are not rendering the active class-specific skill kit.');
assert(classSkills.includes("shortName: 'RUSH'") && classSkills.includes("shortName: 'BREAK'") && classSkills.includes("shortName: 'GUARD'") && classSkills.includes("shortName: 'SHIFT'") && classSkills.includes("shortName: 'LOCK'") && classSkills.includes("shortName: 'SPLIT'") && classSkills.includes("shortName: 'WELL'") && classSkills.includes("shortName: 'HACK'") && classSkills.includes("shortName: 'CHAIN'"), 'One or more level-one class skill kits are missing.');
assert(sim.includes("operatorWeaponFamilyForClass(build.operatorClass)") && sim.includes('currentWeapon: classWeapon') && sim.includes('CLASS ARSENAL LOCK'), 'Class deployments are missing owned-family boot selection or runtime arsenal enforcement.');
assert(sim.includes('export const weaponHandlingProfiles') && sim.includes("stance: 'mobile'") && sim.includes("stance: 'breach'") && sim.includes("stance: 'precision'") && sim.includes('handling.shotVelocityRetention') && sim.includes('handling.reloadMoveScale') && sim.includes('handling.ventMoveScale'), 'P8-F simulation handling identity is missing stance, recoil, movement, reload, or vent differentiation.');
assert(renderer.includes('weaponHandlingProfiles') && renderer.includes('dataset.weaponHandling') && renderer.includes("handling.reloadStyle === 'chamber-feed'") && renderer.includes("handling.ventStyle === 'coil-quench'") && renderer.includes('handling.recoilVisual') && renderer.includes('cameraFeedback?.worldOffsetX'), 'P8-F Three renderer is missing family stance/recoil/reload/vent/muzzle or shared camera handling.');
assert(combat.includes('weaponHandlingProfiles[p.currentWeapon]') && combat.includes('handling.muzzleLength') && combat.includes('cameraFeedback.canvasOffsetX') && cameraFeedbackSource.includes('weaponHandlingProfiles[input.weapon].cameraKick'), 'P8-F Canvas fallback/shared camera response is missing family muzzle or camera handling.');
assert(feedbackSource.includes("cue === 'carbine' ? 4") && feedbackSource.includes("cue === 'breacher' ? .58") && feedbackSource.includes("cue === 'rail' ? .5"), 'P8-F weapon haptics are not family-specific.');
assert(classSkills.includes("weaponFamily: 'breacher'") && classSkills.includes("weaponFamily: 'rail'") && classSkills.includes("weaponFamily: 'carbine'") && classSkills.includes('classSkillFamilyForClass'), 'P8-G class skills are not explicitly bound to the class-owned weapon family contract.');
assert(meta.includes('function applyClassSkillFamilyInfluence') && meta.includes('build.classSkillFamily.family = activeWeaponFamilyForProfile(profile)') && meta.includes("skill.sources.push(`frame:${identity}`)") && meta.includes("skill.sources.push(`singular:${item.singularTrait}`)") && meta.includes("network:predictive-lead") && meta.includes("network:signal-compression"), 'P8-G class-skill tuning is missing frame, affix, progression, or Singular influence.');
assert(classSkillFamilyInfluence.includes('item.slot !== family') && !classSkillFamilyInfluence.includes('item.id'), 'P8-G skill migration must be family-aware without binding class skills to a specific weapon item ID.');
assert(sim.includes('const familyBound = !!base.weaponFamily && base.weaponFamily === family.family') && sim.includes('range: familyBound ? family.rangeMul : 1') && sim.includes('chainBonus: familyBound ? family.chainBonus : 0'), 'P8-G runtime ability config is not consuming class-owned family tuning.');
assert(sim.includes("projectile.weapon = state.build.classSkillFamily.family ?? 'carbine'") && sim.includes('projectile.weapon === state.build.classSkillFamily.family') && sim.includes('const familyExecution ='), 'P8-G shared skill mechanics still contain weapon-specific family assumptions.');
assert(meta.includes("A hit from your class-owned armament consumes a target mark") && !meta.includes("A Rail Lance hit consumes a target mark"), 'P8-G shared Execution Trace lens still describes a Rail-only skill contract.');
assert(armory.includes('Class Skill → Weapon Family → Lens/Evolution → Specialization/Capstone') && armory.includes('aria-label="Class skill hierarchy"') && armory.includes('skill-hierarchy-grid') && armory.includes('SHARED LENSES') && armory.includes('CLASS EVOLUTIONS') && armory.includes('activeSkillBuild.sources.length'), 'P8-H Skills UI does not expose the class → family → lens/evolution → specialization/capstone hierarchy.');
assert(armory.includes('classSkillIconAssets') && armory.includes('weaponIconAssets') && armory.includes('family-linked skill tuning') && armory.includes('capstoneInteractionFor(profile, selectedModId)'), 'P8-H Skills UI is missing class/family iconography or live capstone/family state.');
assert(classBuildCss.includes('.skill-path-overview') && classBuildCss.includes('.skill-hierarchy-grid') && classBuildCss.includes('.skill-option-group > button') && classBuildCss.includes('@media (pointer: coarse)') && classBuildCss.includes('min-height: 52px') && classBuildCss.includes('orientation: landscape'), 'P8-H Skills hierarchy styling is missing touch targets or mobile-landscape reflow.');
assert(armory.includes('activeAbilityKit') && armory.includes('LV1 KIT //') && armory.includes("../game/classSkills"), 'Build does not surface class-specific skills through the lightweight class-skill module.');
assert(browserSmoke.includes('BROWSER_CLASS_SELECTION_PASS') && browserSmoke.includes('BROWSER_CLASS_SELECTION_LAYOUT_PASS') && browserSmoke.includes('BROWSER_MOBILE_ASSET_PASS') && browserSmoke.includes('BROWSER_CLASS_KIT_PASS') && browserSmoke.includes('Breach Rush') && browserSmoke.includes('Fracture Tag') && browserSmoke.includes('Bulwark Pulse'), 'Browser E2E does not exercise the beginner class intake layout and resulting Vanguard skill kit.');
assert(browserSmoke.includes('BROWSER_SKILL_HIERARCHY_PASS') && browserSmoke.includes('Class Skill → Weapon Family') && browserSmoke.includes('SHARED LENSES') && browserSmoke.includes('CLASS EVOLUTIONS'), 'Browser E2E does not exercise the P8-H Build skill hierarchy.');
assert(androidSmoke.includes('ANDROID_CLASS_SELECTION_PASS') && androidSmoke.includes('ANDROID_CLASS_SELECTION_LAYOUT_PASS') && androidSmoke.includes('ANDROID_MOBILE_ASSET_PASS') && androidSmoke.includes('ANDROID_CLASS_KIT_PASS') && androidSmoke.includes('Breach Rush') && androidSmoke.includes('Fracture Tag') && androidSmoke.includes('Bulwark Pulse'), 'Android smoke does not exercise the beginner class intake layout and resulting Vanguard skill kit.');
assert(androidSmoke.includes('ANDROID_SKILL_HIERARCHY_PASS') && androidSmoke.includes('Class Skill → Weapon Family') && androidSmoke.includes('SHARED LENSES') && androidSmoke.includes('CLASS EVOLUTIONS'), 'Android smoke does not exercise the P8-H touch skill hierarchy.');
assert(!app.includes('LV15 Vector Specialization ready') && !app.includes('LV15 // VECTOR SPECIALIZATION + GENERATION VI'), 'Mission debrief still hardcodes Vector specialization copy for every class.');
assert(qolCss.includes('BETA UI QOL // CONTRACT BOARD + INVENTORY DISCOVERY') && qolCss.includes(':focus-visible') && qolCss.includes('.inventory-reset'), 'QoL stylesheet is missing focus visibility or inventory reset treatment.');
assert(hubCss.includes('PLAYTEST READINESS VISIBILITY') && hubCss.includes('.contract-readiness.high-gap'), 'Contract readiness styling is missing.');
const polishCss = read('src/uiPolish.css');
assert(polishCss.includes('.command-action-row') && polishCss.includes('.stats-help') && polishCss.includes('.compact-discovery'), 'UI polish stylesheet is incomplete.');

const mobileInspectorCss = read('src/part12.css');
assert(mobileInspectorCss.includes('ANDROID ITEM INSPECTOR SINGLE SCROLLER') && mobileInspectorCss.includes('overflow-y: auto') && mobileInspectorCss.includes('.gear-layout .item-inspector.open .inspector-scroll') && mobileInspectorCss.includes('overflow: visible') && mobileInspectorCss.includes('touch-action: auto'), 'Android item inspector still depends on a nested touch-scroll pane.');

for (const inset of ['safe-area-inset-top', 'safe-area-inset-right', 'safe-area-inset-bottom', 'safe-area-inset-left']) {
  assert(mobileCombatCss.includes(`env(${inset})`) || rootCss.includes(`env(${inset})`), `mobile combat CSS is missing ${inset} handling`);
}
assert(browserWorkflow.includes('mobile-landscape') && browserWorkflow.includes('matrix.viewport'), 'Browser E2E must cover both desktop and mobile-landscape viewports');
assert(androidWorkflow.includes('require_release_signing') && androidWorkflow.includes('REQUIRE_RELEASE_SIGNING') && androidWorkflow.includes('Release signing is required for this run'), 'Manual Android release-candidate runs must fail closed when persistent release signing is required but unavailable');
assert(browserSmoke.includes('BROWSER_MOBILE_LAYOUT_PASS') && browserSmoke.includes('moveDockOverlap') && browserSmoke.includes('undersized'), 'Browser mobile E2E is missing safe-area/touch-target layout assertions');
assert(androidSmoke.includes('ANDROID_MOBILE_LAYOUT_PASS') && androidSmoke.includes('moveDockOverlap') && androidSmoke.includes('undersized'), 'Android smoke is missing safe-area/touch-target layout assertions');
assert(androidSmoke.includes('ANDROID_MOBILE_MENU_PASS') && androidSmoke.includes("=== 'operations'") && androidSmoke.includes('primaryCount !== 5') && androidSmoke.includes('verticalOverflow > 2'), 'Android smoke is not validating the Tactical Command navigation hierarchy, mobile rail, and no-scroll fit.');
assert(androidSmoke.includes('ANDROID_LIFECYCLE_RESUME_PASS'), 'Android lifecycle pause/resume validation is missing');
assert(androidResumeGate.includes("canvas[data-render-tier]") && androidResumeGate.includes('[aria-label="Touch combat controls"]') && androidResumeGate.includes('.move-stick') && !androidResumeGate.includes("text.includes('field coach')"), 'Android lifecycle resume gate must detect the restored combat renderer/controls without depending on tutorial coach text');
assert(androidSmokeShell.includes('--activity-reorder-to-front') && androidSmokeShell.includes('RESUME_PID') && androidSmokeShell.includes('ANDROID_LIFECYCLE_PROCESS_RECLAIM') && androidSmokeShell.includes('LIFECYCLE_ATTEMPT') && androidSmokeShell.includes('re-establishing combat before retrying pause/resume') && androidSmokeShell.includes('ANDROID_RESUME_PROCESS_MODE=preserved'), 'Android lifecycle smoke must recover from an incidental process reclaim, retry pause/resume, and require a preserved-process combat resume before passing');
assert(androidResumeGate.includes("['preserved', 'reclaimed']") && androidResumeGate.includes('resumeProcessMode') && androidResumeGate.includes('ANDROID_LIFECYCLE_RESUME_PASS process='), 'Android lifecycle resume gate must validate and report the process preservation/reclaim mode');
assert(androidSmoke.includes('function validRenderBudget(value)') && androidSmoke.includes('validRenderBudget(renderTier.budget)') && androidSmoke.includes('validRenderBudget(resumed.budget)'), 'Android render-budget QA must parse telemetry structurally instead of relying on an escaped regex');
assert(androidSmoke.includes("'Android runtime scalability telemetry'") && androidSmoke.includes('canvas?.dataset.renderTier') && androidSmoke.includes('canvas?.dataset.renderBudget') && androidSmoke.includes('canvas?.dataset.runtimeAnimationLod') && androidSmoke.includes('canvas?.dataset.audioVirtualization'), 'Android smoke must wait for render/runtime scalability telemetry before validating the mobile runtime tier.');


assert(armory.includes('BASE / IMPLICIT') && armory.includes('EXPLICIT MODIFIERS') && armory.includes('AUGMENTS') && armory.includes('BUILD LINKS') && armory.includes('LOADOUT IMPACT'), 'P8.5-J item inspection hierarchy must prioritize base/implicit, explicit mods, augments, build links, then equipped impact.');
assert(armory.includes('LOCAL STATS') && armory.includes('GLOBAL STATS') && armory.includes('SKILL LINKS') && armory.includes('SPECIALIZATION GEAR LINK') && armory.includes('SINGULAR RULE') && armory.includes('itemStatDefinitions(equipped)') && armory.includes('classSkillFamily.sources'), 'P8.5-J generated build links must compare local/global stats, skill links, specialization links, and Singular rules.');
assert(armory.includes('Advanced metadata & provenance') && armory.includes('SOURCE / PROVENANCE') && !armory.includes('GEAR SCORE') && !armory.includes('gear score'), 'P8.5-J must move provenance/advanced telemetry deeper and must not introduce a gear-score number.');
assert(equipmentCss.includes('P8.5-J MOBILE ARMORY BUILD LINKS') && equipmentCss.includes('.build-links-panel') && equipmentCss.includes('.build-link-diff.gain') && equipmentCss.includes('.build-link-diff.loss'), 'P8.5-J build-link comparison styling is missing gain/loss and mobile layout treatment.');

console.log('UI_READABILITY_PASS discovery=hidden contractGear=unidentified targetHp=strong missionLoot=reviewable hierarchy=polished mobile=desktop+landscape-safe');
