import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

function read(path: string) {
  return readFileSync(resolve(process.cwd(), path), 'utf8');
}
function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

const armory = read('src/components/Armory.tsx');
const combat = read('src/components/GameCanvas.tsx');
const sim = read('src/game/sim.ts');
const meta = read('src/game/meta.ts');
const classSkills = read('src/game/classSkills.ts');
const renderer = read('src/game/threeCombatRenderer.ts');
const css = read('src/readability.css');
const shipHub = read('src/components/ShipHub.tsx');
const statsPanel = read('src/components/PlayerStatsPanel.tsx');
const hubVisual = read('src/components/CommandHubVisual.tsx');
const hubCss = read('src/commandHub.css');
const campaignCss = read('src/part11.css');
const menuOverhaulCss = read('src/menuOverhaul.css');
const app = read('src/App.tsx');
const equipmentCss = read('src/equipmentBay.css');
const missionCss = read('src/part4.css');
const objectiveCss = read('src/part7.css');
const rootCss = read('src/index.css');
const mobileCombatCss = read('src/mobileCombatReadability.css');
const qolCss = read('src/qol.css');
const classBuildCss = read('src/classBuilds.css');
const classSelect = read('src/components/ClassSelectScreen.tsx');
const classSelectCss = read('src/classSelection.css');
const mobileUiAssets = read('src/game/mobileUiAssets.ts');
const vanguardRushIcon = read('public/assets/ui/skills/vanguard-rush.svg');
const vectorLockIcon = read('public/assets/ui/skills/vector-lock.svg');
const systemsChainIcon = read('public/assets/ui/skills/systems-chain.svg');
const carbineIcon = read('public/assets/ui/weapons/carbine.svg');
const breacherIcon = read('public/assets/ui/weapons/breacher.svg');
const railIcon = read('public/assets/ui/weapons/rail.svg');
const browserSmoke = read('scripts/browser-runtime-smoke.mjs');
const androidSmoke = read('scripts/android-runtime-smoke.mjs');
const androidResumeGate = androidSmoke.match(/if \(resumeOnly\) \{[\s\S]*?process\.exit\(0\);\n\}/)?.[0] ?? '';
const androidSmokeShell = read('scripts/android-runtime-smoke.sh');
const browserWorkflow = read('.github/workflows/browser-e2e.yml');
const androidWorkflow = read('.github/workflows/android-apk.yml');
const parallaxDebt = read('src/game/parallaxDebt.ts');
const scaling = read('src/game/scaling.ts');

assert(shipHub.includes('PARALLAX INTEL // ROUTE RECONSTRUCTION // LV15–18') && shipHub.includes('parallaxDebtNextRequiredLevel'), 'Campaign UI must present the expanded LV15–18 Parallax Debt progression and its level gates.');
assert(shipHub.includes('PARALLAX DEBT // CONTRACT') && shipHub.includes('parallaxChoice.choices.map') && shipHub.includes('chooseParallaxDebtBranch'), 'Contract and campaign surfaces must expose the Parallax Debt decision and closing branch.');
assert(shipHub.includes('PARALLAX INTEL // ROUTE RECONSTRUCTION // LV15–18') && shipHub.includes('parallax-intel-summary') && shipHub.includes('parallax-phase-grid') && shipHub.includes('parallax-route-grid') && shipHub.includes('UNRESOLVED BOUNDARY // DO NOT OVERCLAIM'), 'P1.18 dedicated Parallax Intel dossier is missing phase, route, or evidence-boundary presentation.');
assert(shipHub.includes('parallaxDebtIntel(campaign)') && shipHub.includes('parallaxFindings.length') && shipHub.includes('CLASSIFIED UNTIL FALSE HORIZON'), 'Parallax Intel presentation is not synchronized to campaign evidence and route reveal state.');
assert(campaignCss.includes('P1.18 // PARALLAX DEBT INTEL DOSSIER') && campaignCss.includes('.parallax-phase-grid') && campaignCss.includes('.parallax-bank-grid') && campaignCss.includes('@media (orientation:landscape) and (max-height:650px)'), 'Parallax Intel dossier is missing responsive/mobile-landscape presentation coverage.');
assert(app.includes('getParallaxDebtContract(campaign, profile.level)'), 'Contract generation must enforce Parallax Debt operator-level gates.');
assert(parallaxDebt.includes("authoredContracts: 12") && parallaxDebt.includes("id: 'expose-route'") && parallaxDebt.includes("id: 'hold-route'") && parallaxDebt.includes('Common Reference') && parallaxDebt.includes('Private Vector'), 'Parallax Debt content must preserve the nine-mission spine and author both final three-operation branches.');
assert(scaling.includes("contract.campaignChapter === 'parallax-debt'") && scaling.includes("8 + Math.floor((contract.campaignStep ?? 0) / 3)"), 'Parallax Debt must retain late-game tier scaling across its LV15–18 phases.');

assert(meta.includes("name: 'Void Ram'") && meta.includes("name: 'Breach Cascade'") && meta.includes("name: 'Counterfort'"), 'Vanguard capstone interaction definitions are incomplete.');
assert(meta.includes("name: 'Induction Sink'") && meta.includes("name: 'Recursive Bus'") && meta.includes("name: 'Mesh Reflux'"), 'Systems capstone interaction definitions are incomplete.');
assert(meta.includes("name: 'Thermal Shunter'") && meta.includes("specializationIds: ['grid-weaver', 'capacitor-conductor', 'thermal-shunter']") && sim.includes('systemsCrossfeed') && sim.includes('THERMAL CROSSFIRE'), 'P5.6 Systems third specialization is missing from class metadata or combat feedback.');
assert(statsPanel.includes('capstoneInteractionFor') && statsPanel.includes('CAPSTONE ${activeCapstone.name}'), 'Build Stats does not surface active class capstone interactions.');
assert(armory.includes('availableSpecializations.map'), 'Operator Network UI must render every class specialization from shared metadata.');
assert(armory.includes('CAPSTONE LINK //') && armory.includes('capstoneInteractionFor'), 'Build Skills UI does not surface active specialization/evolution capstone links.');
assert(!armory.includes('Review faction doctrines'), 'Equipment Bay still advertises undiscovered faction doctrine targets.');
assert(!armory.includes('2 PIECE'), 'Equipment Bay still exposes 2-piece set targets.');
assert(!armory.includes('4 PIECE'), 'Equipment Bay still exposes 4-piece set targets.');
assert(!armory.includes('setName'), 'Equipment Bay still renders undiscovered set names.');
assert(armory.includes('PRIMARY EFFECT'), 'Item inspector is missing plain-language quick read.');
assert(armory.includes('RULE-CHANGER'), 'Rarity meaning cues are missing from gear UI.');
assert(armory.includes('activeDoctrineStates'), 'Discovered-only loadout interactions are missing.');

assert(combat.includes('HEALTH EXPOSED'), 'Combat UI does not explicitly call out broken armor and exposed health.');
assert(combat.includes('Focused hostile status'), 'Focused hostile health readout is missing.');
assert(combat.includes('DROP ON DECK'), 'Ground-loot explanation is missing from combat HUD.');
assert(combat.includes('lootLabel(drop.rarity)'), 'High-value ground loot does not receive a readable world label.');
assert(renderer.includes("enemy.role === 'elite' ? 2.2 : 1.9"), 'Three.js hostile bars are still too small for mobile readability.');
assert(renderer.includes('0xff725f') && renderer.includes('0x8ee8ff') && renderer.includes('THREE.AdditiveBlending') && renderer.includes('toneMapped: false'), 'Three.js hostile bars are not using the bright mobile treatment.');
assert(css.includes('.target-readout') && css.includes('.gear-quick-read') && css.includes('.loot-radar'), 'Readability stylesheet is incomplete.');
assert(armory.includes('gear-deep-details') && css.includes('.gear-deep-details'), 'Gear inspector does not separate essential comparison from advanced telemetry.');
assert(equipmentCss.includes('gear-layout.has-selection::before') && equipmentCss.includes('width: min(72vw, 760px)'), 'Landscape mobile gear inspector is missing focused modal treatment.');
assert(equipmentCss.includes('.item-inspector .sheet-close') && equipmentCss.includes('@media (pointer: coarse)'), 'Gear inspector cannot be reliably closed on coarse-pointer landscape devices.');
assert(equipmentCss.includes('MOBILE INSPECTOR SCROLL RELIABILITY') && equipmentCss.includes('touch-action: pan-y') && equipmentCss.includes('-webkit-overflow-scrolling: touch') && equipmentCss.includes('height: calc(100dvh'), 'Mobile gear inspector is not a bounded touch-scroll surface.');
assert(armory.includes('inspector-header') && armory.includes('inspector-scroll') && armory.includes('gear-summary-grid') && armory.includes('impact-stat'), 'Item inspector redesign hierarchy is missing.');
assert(equipmentCss.includes('ITEM INSPECTOR REDESIGN') && equipmentCss.includes('grid-template-rows: auto minmax(0, 1fr) auto') && equipmentCss.includes('.inspector-scroll') && equipmentCss.includes('overflow: hidden'), 'Item inspector is not using the fixed-header/scroll-body/action-dock layout.');
assert(equipmentCss.includes('ITEM INSPECTOR LAZY-CSS CASCADE GUARD') && equipmentCss.includes('.gear-layout .item-inspector.open'), 'Lazy Armory CSS can override the redesigned inspector grid.');
assert(armory.includes("useState<string | null>(null)") && armory.includes("newLootIds.length > 0 ? 'new' : 'all'") && armory.includes('item-inspector-backdrop'), 'Recovered loot should open as a dismissible filtered list rather than trapping the player in an inspector.');
assert(equipmentCss.includes('MOBILE INSPECTOR ESCAPE RELIABILITY') && equipmentCss.includes('.item-inspector-backdrop') && equipmentCss.includes('pointer-events: none'), 'Mobile item inspector backdrop/escape behavior is missing.');
assert(css.includes('DEBRIEF RARITY COLORS') && css.includes('.recovery-review-card.rarity-singular') && css.includes('.recovery-review-card.rarity-prototype'), 'Debrief recovery cards are missing rarity color treatment.');
assert(objectiveCss.includes('MOBILE OBJECTIVE COMPACTNESS OVERRIDE') && objectiveCss.includes('width: min(300px, 34vw)') && objectiveCss.includes('.post-clear-objective small { display: none; }'), 'Post-clear objective guidance can still cover too much of the mobile combat view.');
assert(missionCss.includes('RESPONSIVE MISSION SURFACE RELIABILITY') && missionCss.includes('overflow-y: auto'), 'Combat completion overlays can still extend outside the visible viewport.');
assert(missionCss.includes('place-items: start center') && missionCss.includes('height: 100dvh'), 'Mission debrief can still center oversized content outside the scrollable viewport.');
assert(missionCss.includes('max-height: 900px'), 'Short landscape viewport scaling regression coverage is missing.');
assert(app.includes('RECOVERED EQUIPMENT // REVIEW') && app.includes('Confirm discard'), 'Mission debrief is missing acquired-gear review/discard controls.');
assert(app.includes('discardRecoveredItem') && app.includes('discardItem(current, itemId)'), 'Debrief discard is not wired to persistent profile inventory.');
assert(app.includes('debriefRunSequenceRef') && app.includes('current?.runId === debriefRunId'), 'Telemetry completion can still mutate a later mission debrief.');
assert(app.includes('LOCAL SAVE FAILED') && app.includes('!saveGameState(profile, campaign)') && app.includes("current === persistenceWarning ? '' : current") && shipHub.includes("const displayedStatusMessage = statusMessage ||") && shipHub.includes("role={statusMessage ? 'alert' : 'status'}"), 'Local persistence failures are not surfaced reliably to an already-mounted ShipHub.');
assert(shipHub.includes('traceRequestIdRef') && shipHub.includes('const requestId = ++traceRequestIdRef.current') && shipHub.includes('traceRequestIdRef.current !== requestId'), 'Operations trace loading can still let an older request overwrite a newer selection.');
assert(!shipHub.includes('bossSingularNames'), 'Contract Board still imports unrecovered boss gear names.');
assert(!shipHub.includes('locationSingularNames'), 'Contract Board still imports unrecovered location gear names.');
assert(!shipHub.includes('factionEquipmentNames'), 'Ship UI still exposes unrecovered faction gear names.');
assert(!shipHub.includes('DEDICATED SINGULAR POOL'), 'Contract Board still advertises a named Singular pool.');
assert(!shipHub.includes('LOCATION CHASE POOL'), 'Contract Board still advertises location chase gear before discovery.');
assert(!shipHub.includes('RECOVERY CEILING // RL'), 'Contract Board still leads with opaque recovery-level jargon.');
assert(shipHub.includes('EQUIPMENT RECOVERY'), 'Contract Board is missing the discovery-safe equipment explanation.');
assert(shipHub.includes('Frame identities and interactions reveal only after recovery.'), 'Faction panel is missing acquisition-first discovery guidance.');
assert(shipHub.includes("useState<Tab>('overview')"), 'App does not open on the new command overview.');
assert(shipHub.includes("switchTab('stats')"), 'Command hub is missing Player Stats navigation.');
assert(shipHub.includes('CommandHubVisual'), 'Command hub visual is not integrated.');
assert(shipHub.includes('PlayerStatsPanel'), 'Player stats page is not integrated.');
assert(statsPanel.includes('Current build') && statsPanel.includes('Vacuum resistance') && statsPanel.includes('BURST DPS'), 'Player stats page is missing explained final stats.');
assert(statsPanel.includes('createSimulation(build)'), 'Stats page is not using the real combat build for final values.');
assert(hubVisual.includes('command-bridge-schematic') && hubVisual.includes('OPERATOR LV') && hubVisual.includes('GEAR LINK'), 'Opening hub does not visually represent the ship and operator readiness.');
assert(hubVisual.includes('COMMAND READY') && hubVisual.includes('bridge-compact-readiness') && !hubVisual.includes('bridge-gear-panel') && !hubVisual.includes('bridge-gear-strip'), 'Opening Command surface is not using the compact readiness treatment.');
assert(hubCss.includes('.command-overview') && hubCss.includes('.player-stat-grid'), 'Command hub responsive styling is incomplete.');
assert(shipHub.includes("type PrimaryArea = 'command' | 'operations' | 'operator' | 'ship' | 'intel'"), 'Ship Hub has not collapsed navigation into five primary mental models.');
assert(shipHub.includes('command-rail-nav') && shipHub.includes('section-tabs') && shipHub.includes('areaTabs'), 'Tactical Command Deck navigation shell is incomplete.');
assert(!shipHub.includes('aria-label="Ship areas"'), 'Legacy nine-tab primary navigation is still rendered.');
assert(menuOverhaulCss.includes('.command-rail') && menuOverhaulCss.includes('.tactical-workspace') && menuOverhaulCss.includes('.command-bridge') && menuOverhaulCss.includes('max-height: 650px') && menuOverhaulCss.includes('max-height: 380px') && menuOverhaulCss.includes('.ship-hub.area-command .hub-resource-ribbon'), 'Tactical Command Deck responsive visual system is incomplete at standard or ultra-short landscape heights.');
assert(menuOverhaulCss.includes('prefers-reduced-motion') && menuOverhaulCss.includes('safe-area-inset-bottom'), 'Menu overhaul is missing reduced-motion or safe-area handling.');
assert(shipHub.includes("operations: ['contracts', 'operations']") && shipHub.includes("intel: ['campaign', 'stories', 'factions']") && shipHub.includes("stats: 'Stats'") && shipHub.includes("operations: 'Uplink'"), 'Primary information architecture still mixes campaign/intel with deployment or uses ambiguous Stats/Uplink labels.');
assert(!shipHub.includes('<button className="hub-build-button" onClick={onOpenBuild}>Equipment</button>') && !shipHub.includes('<b>Tune loadout</b>') && shipHub.includes('command-priority-panel'), 'Command overview still duplicates Build navigation or lacks contextual priorities.');
assert(armory.includes("gear: 'Loadout'") && armory.includes("reconstruct: 'Crafting'") && armory.includes("network: 'Progression'") && armory.includes("protocols: 'Skills'"), 'Build tabs still expose implementation terminology instead of player-facing labels.');
assert(menuOverhaulCss.includes('UI SIMPLIFICATION // PRIORITY-FIRST COMMAND + CONTRACT CARDS') && mobileCombatCss.includes('MOBILE HUD INFORMATION BUDGET'), 'UI simplification styling is missing command/contract or mobile-HUD coverage.');
assert(shipHub.includes("overview: 'Overview'") && shipHub.includes("const pageTitle = tab === 'overview' ? 'Overview'"), 'Command overview still repeats Command/Tasking language instead of using a neutral overview page title.');
assert(combat.includes('visibleConsumables') && combat.includes("consumableDefinitions.filter(item => consumableStock[item.id] > 0)") && mobileCombatCss.includes('max-width: min(360px, 30vw)'), 'Mobile combat still reserves persistent HUD space for empty consumables or oversized mission alerts.');
assert(browserSmoke.includes("keyboardActivateButton('Operations')") && browserSmoke.includes("keyboardActivateButton('Contracts')"), 'Browser E2E does not follow the new Command > Operations > Contracts hierarchy.');
assert(browserSmoke.includes('BROWSER_MOBILE_MENU_PASS') && browserSmoke.includes('primaryCount !== 5'), 'Browser E2E is missing mobile Tactical Command rail layout coverage.');
assert(armory.includes("import '../menuOverhaul.css';"), 'Equipment surface is not using the Tactical Command visual system.');
assert(!shipHub.includes('No urgent ship tasks'), 'Empty priority chrome is still rendered when nothing needs attention.');
assert(!shipHub.includes('command-nav-grid'), 'Overview still duplicates the full tab navigation.');
assert((statsPanel.match(/Weapon stat glossary/g) ?? []).length === 1, 'Weapon stat help should be shared once, not repeated per weapon.');
assert(!statsPanel.includes('What these numbers mean'), 'Per-weapon duplicate glossary remains.');
assert(armory.includes('compact-discovery') && !armory.includes('Build changes save automatically on this device.'), 'Equipment Bay still shows repetitive instructional/status chrome.');
assert(combat.includes('mission-build-label') && !combat.includes('objective-progress-chip') && combat.includes("const focusEnemy = hud.bossActive ? null : lockedHostile") && combat.includes("(!coarse || hud.classActive)"), 'Combat HUD still duplicates objective guidance or permanently renders secondary target/class panels.');
assert(combat.includes('hostileRouteMode') && combat.includes('objectiveRouteMode'), 'Combat cleanup guidance is missing obstacle-aware route state.');
const gameRootRule = rootCss.match(/\.game-root\s*\{[^}]*\}/)?.[0] ?? '';
const gameCanvasRule = rootCss.match(/\.game-canvas\s*\{[^}]*\}/)?.[0] ?? '';
const touchStickRule = rootCss.match(/\.touch-stick\s*\{[^}]*\}/)?.[0] ?? '';
const touchButtonRule = rootCss.match(/\.touch-button\s*\{[^}]*\}/)?.[0] ?? '';
const overlayRule = rootCss.match(/\.overlay\s*\{[^}]*\}/)?.[0] ?? '';
const overlayCardRule = rootCss.match(/\.overlay-card\s*\{[^}]*\}/)?.[0] ?? '';
assert(!combat.includes("document.addEventListener('touchmove'") && !combat.includes("document.addEventListener('gesturestart'"), 'Combat still suppresses touch gestures at document scope.');
assert(!gameRootRule.includes('touch-action: none'), 'Combat root still disables gestures for descendant overlays.');
assert(gameCanvasRule.includes('touch-action: none') && touchStickRule.includes('touch-action: none') && touchButtonRule.includes('touch-action: manipulation'), 'Combat input surfaces are missing scoped touch-action protection.');
assert(overlayRule.includes('touch-action: pan-y') && overlayRule.includes('overflow-y: auto') && overlayCardRule.includes('touch-action: pan-y') && overlayCardRule.includes('overflow-y: auto'), 'Combat overlays are not explicit vertical touch-scroll surfaces.');
assert(shipHub.includes('OPERATOR READINESS') && shipHub.includes('readiness-chip'), 'Contract board is missing visible operator/monster readiness guidance.');
assert(shipHub.includes("type ContractSort = 'level-match'") && shipHub.includes('aria-label="Search contracts"') && shipHub.includes('contract-card-readiness') && !shipHub.includes('contract-quick-deploy') && shipHub.includes("filter === 'ready'"), 'Contract Board QoL search, level-match sorting, ready filtering, or simplified card hierarchy is missing.');
assert(armory.includes("type InventoryFilter = 'all' | 'new' | 'usable'") && armory.includes('Clear storage filters') && armory.includes('Usable now') && armory.includes("window.addEventListener('keydown', closeInspector)"), 'Equipment storage QoL filtering, reset, or Escape-to-close behavior is missing.');
assert(armory.includes('OPERATOR CLASS // FIELD DOCTRINE') && armory.includes('class-resonance-strip') && armory.includes('availableSpecializations') && armory.includes('class-freedom-note'), 'Operator class selection, class-specific specialization routes, or open-build guidance is missing.');
assert(armory.includes('CLASS RESONANCE') && armory.includes('itemBuildAffinities(item)') && armory.includes('class-resonance-pill'), 'Equipment UI does not surface class resonance on recovered gear.');
assert(classBuildCss.includes('.operator-class-grid') && classBuildCss.includes('.class-resonance-strip') && classBuildCss.includes('.gear-class-fit') && classBuildCss.includes('max-height: 650px'), 'Operator class/build styling is incomplete or missing mobile-landscape coverage.');
assert(statsPanel.includes('build-class-summary') && statsPanel.includes('gearResonanceForProfile'), 'Player Stats does not expose the active class and gear resonance state.');
assert(app.includes("type Screen = 'class'") && app.includes("initialGameState.profile.classSelectionComplete ? 'ship' : 'class'") && app.includes('ClassSelectScreen'), 'Fresh profiles are not routed through a dedicated class selection screen.');
assert(classSelect.includes('Pick your combat role') && classSelect.includes('Gear is not class-locked') && classSelect.includes('Choose the role that sounds fun') && classSelect.includes('Select ${definition.name} class') && classSelect.includes('aria-label={`Confirm ${selected.name}`}') && classSelect.includes('Play {selected.name}'), 'Class intake is missing beginner-first role selection, build-freedom guidance, or confirmation controls.');
assert(classSelect.includes('classIntakeCopy') && classSelect.includes('HOW TO PLAY') && classSelect.includes('YOUR FIRST 3 ABILITIES') && classSelect.includes('Build details for later') && classSelect.includes('operatorClassOnboardingRecovery') && classSelect.includes('classAbilityKits'), 'Class intake does not lead with plain-language playstyle, starting abilities, or progressive disclosure for advanced build details.');
assert(mobileUiAssets.includes('/assets/ui/classes/vanguard.svg') && mobileUiAssets.includes('/assets/ui/classes/vector.svg') && mobileUiAssets.includes('/assets/ui/classes/systems.svg'), 'Mobile UI asset catalog is missing lightweight authored class crests.');
assert(mobileUiAssets.includes('vanguard-rush.svg') && mobileUiAssets.includes('vector-lock.svg') && mobileUiAssets.includes('systems-chain.svg') && mobileUiAssets.includes('weaponIconAssets'), 'Mobile UI asset catalog is missing class-skill or weapon icon mappings.');
assert(classSelect.includes('classSkillIconAssets') && classSelect.includes('operatorClassIconAssets') && classSelect.includes('class-skill-key'), 'Class intake is not using the mobile icon asset catalog.');
assert(combat.includes('classSkillIconAssets') && combat.includes('weaponIconAssets') && combat.includes('operatorClassIconAssets') && combat.includes('class-mechanic-hud'), 'Combat HUD is missing mobile class/skill/weapon icon integration.');
assert([vanguardRushIcon, vectorLockIcon, systemsChainIcon, carbineIcon, breacherIcon, railIcon].every(icon => icon.includes('<svg') && icon.includes('viewBox=')), 'One or more mobile SVG combat assets are malformed.');
assert(classSelectCss.includes('.class-choice-grid') && classSelectCss.includes('.class-selected-panel') && classSelectCss.includes('.class-starting-kit-grid') && classSelectCss.includes('.class-card-kit img') && classSelectCss.includes('.class-skill-key img') && classSelectCss.includes('.class-advanced-details') && classSelectCss.includes('.class-mechanic-hud') && classSelectCss.includes('.game-root.class-vanguard') && classSelectCss.includes('.game-root.class-vector') && classSelectCss.includes('.game-root.class-systems') && classSelectCss.includes('max-height: 650px') && classSelectCss.includes('safe-area-inset-left'), 'Class intake/skill-kit/combat feedback styling is missing progressive disclosure, class theming, landscape, or safe-area coverage.');
assert(combat.includes('getClassMechanicStatus') && combat.includes('class-mechanic-hud') && combat.includes('Class signature status'), 'Combat HUD is missing live class signature feedback.');
assert(combat.includes('getAbilityKit') && combat.includes('abilityKit.map') && !combat.includes('abilityMeta.map'), 'Combat controls are not rendering the active class-specific skill kit.');
assert(classSkills.includes("shortName: 'RUSH'") && classSkills.includes("shortName: 'BREAK'") && classSkills.includes("shortName: 'GUARD'") && classSkills.includes("shortName: 'SHIFT'") && classSkills.includes("shortName: 'LOCK'") && classSkills.includes("shortName: 'SPLIT'") && classSkills.includes("shortName: 'WELL'") && classSkills.includes("shortName: 'HACK'") && classSkills.includes("shortName: 'CHAIN'"), 'One or more level-one class skill kits are missing.');
assert(sim.includes("currentWeapon: build.operatorClass === 'vanguard' ? 'breacher'") && sim.includes("build.operatorClass === 'vector' ? 'rail'"), 'Class deployments do not begin with distinct preferred weapons in hand.');
assert(armory.includes('Skill Lenses') && armory.includes('activeAbilityKit') && armory.includes('LV1 KIT //') && armory.includes("../game/classSkills"), 'Build does not surface class-specific skills through the lightweight class-skill module.');
assert(browserSmoke.includes('BROWSER_CLASS_SELECTION_PASS') && browserSmoke.includes('BROWSER_CLASS_SELECTION_LAYOUT_PASS') && browserSmoke.includes('BROWSER_MOBILE_ASSET_PASS') && browserSmoke.includes('BROWSER_CLASS_KIT_PASS') && browserSmoke.includes('Breach Rush') && browserSmoke.includes('Fracture Tag') && browserSmoke.includes('Bulwark Pulse'), 'Browser E2E does not exercise the beginner class intake layout and resulting Vanguard skill kit.');
assert(androidSmoke.includes('ANDROID_CLASS_SELECTION_PASS') && androidSmoke.includes('ANDROID_CLASS_SELECTION_LAYOUT_PASS') && androidSmoke.includes('ANDROID_MOBILE_ASSET_PASS') && androidSmoke.includes('ANDROID_CLASS_KIT_PASS') && androidSmoke.includes('Breach Rush') && androidSmoke.includes('Fracture Tag') && androidSmoke.includes('Bulwark Pulse'), 'Android smoke does not exercise the beginner class intake layout and resulting Vanguard skill kit.');
assert(!app.includes('LV15 Vector Specialization ready') && !app.includes('LV15 // VECTOR SPECIALIZATION + GENERATION VI'), 'Mission debrief still hardcodes Vector specialization copy for every class.');
assert(qolCss.includes('BETA UI QOL // CONTRACT BOARD + INVENTORY DISCOVERY') && qolCss.includes(':focus-visible') && qolCss.includes('.inventory-reset'), 'QoL stylesheet is missing focus visibility or inventory reset treatment.');
assert(hubCss.includes('PLAYTEST READINESS VISIBILITY') && hubCss.includes('.contract-readiness.high-gap'), 'Contract readiness styling is missing.');
const polishCss = read('src/uiPolish.css');
assert(polishCss.includes('.command-action-row') && polishCss.includes('.stats-help') && polishCss.includes('.compact-discovery'), 'UI polish stylesheet is incomplete.');

const mobileInspectorCss = read('src/part12.css');
assert(mobileInspectorCss.includes('ANDROID ITEM INSPECTOR SINGLE SCROLLER') && mobileInspectorCss.includes('overflow-y: auto') && mobileInspectorCss.includes('.gear-layout .item-inspector.open .inspector-scroll') && mobileInspectorCss.includes('overflow: visible') && mobileInspectorCss.includes('touch-action: auto'), 'Android item inspector still depends on a nested touch-scroll pane.');

for (const inset of ['safe-area-inset-top', 'safe-area-inset-right', 'safe-area-inset-bottom', 'safe-area-inset-left']) {
  assert(mobileCombatCss.includes(`env(${inset})`) || rootCss.includes(`env(${inset})`), `mobile combat CSS is missing ${inset} handling`);
}
assert(browserWorkflow.includes('mobile-landscape') && browserWorkflow.includes('matrix.viewport'), 'Browser E2E must cover both desktop and mobile-landscape viewports');
assert(androidWorkflow.includes('require_release_signing') && androidWorkflow.includes('REQUIRE_RELEASE_SIGNING') && androidWorkflow.includes('Release signing is required for this run'), 'Manual Android release-candidate runs must fail closed when persistent release signing is required but unavailable');
assert(browserSmoke.includes('BROWSER_MOBILE_LAYOUT_PASS') && browserSmoke.includes('moveDockOverlap') && browserSmoke.includes('undersized'), 'Browser mobile E2E is missing safe-area/touch-target layout assertions');
assert(androidSmoke.includes('ANDROID_MOBILE_LAYOUT_PASS') && androidSmoke.includes('moveDockOverlap') && androidSmoke.includes('undersized'), 'Android smoke is missing safe-area/touch-target layout assertions');
assert(androidSmoke.includes('ANDROID_MOBILE_MENU_PASS') && androidSmoke.includes("=== 'operations'") && androidSmoke.includes('primaryCount !== 5') && androidSmoke.includes('verticalOverflow > 2'), 'Android smoke is not validating the Tactical Command navigation hierarchy, mobile rail, and no-scroll fit.');
assert(androidSmoke.includes('ANDROID_LIFECYCLE_RESUME_PASS'), 'Android lifecycle pause/resume validation is missing');
assert(androidResumeGate.includes("canvas[data-render-tier]") && androidResumeGate.includes('[aria-label="Touch combat controls"]') && androidResumeGate.includes('.move-stick') && !androidResumeGate.includes("text.includes('field coach')"), 'Android lifecycle resume gate must detect the restored combat renderer/controls without depending on tutorial coach text');
assert(androidSmokeShell.includes('--activity-reorder-to-front') && androidSmokeShell.includes('RESUME_PID') && androidSmokeShell.includes('RESUME_PID" != "$APP_PID'), 'Android lifecycle smoke must foreground the existing activity and reject process restarts');
assert(androidSmoke.includes('function validRenderBudget(value)') && androidSmoke.includes('validRenderBudget(renderTier.budget)') && androidSmoke.includes('validRenderBudget(resumed.budget)'), 'Android render-budget QA must parse telemetry structurally instead of relying on an escaped regex');
assert(androidSmoke.includes("'Android render tier telemetry'") && androidSmoke.includes('canvas?.dataset.renderTier && canvas?.dataset.renderBudget'), 'Android smoke must wait for renderer telemetry before validating the mobile render tier.');

console.log('UI_READABILITY_PASS discovery=hidden contractGear=unidentified targetHp=strong missionLoot=reviewable hierarchy=polished mobile=desktop+landscape-safe');
