import type { RunMetrics } from '../game/network';

export default function BalanceAudit({ metrics }: { metrics: RunMetrics | null | undefined }) {
  if (!metrics) return <div className="tier-audit empty">No shared tier balance data available.</div>;
  const tiers = Object.entries(metrics.byTier ?? {}).sort((a, b) => Number(a[0]) - Number(b[0]));
  const protocolCombos = Object.entries(metrics.protocolCombinations ?? {}).sort((a, b) => b[1] - a[1]).slice(0, 5);
  if (!tiers.length) return <div className="tier-audit empty">No tier-specific telemetry has been banked yet.</div>;
  return <div className="tier-audit"><div className="tier-audit-head"><b>OPERATION TIER BALANCE AUDIT</b><span>Extraction, attrition, kill pace, recovery quality and modifier distribution from opt-in attempts.</span></div><div className="tier-audit-grid">{tiers.map(([tier, data]) => { const extractRate = data.attempts ? Math.round(data.extractions / data.attempts * 100) : 0; const deepChoice = data.extractions ? Math.round(data.deepRuns / data.extractions * 100) : 0; const avgDamage = data.attempts ? Math.round(data.totalDamageTaken / data.attempts) : 0; const avgDuration = data.attempts ? Math.round(data.totalDuration / data.attempts) : 0; const killInterval = data.killIntervalSamples ? data.killIntervalTotal / data.killIntervalSamples : 0; const avgRq = data.lootItems ? data.lootQualityTotal / data.lootItems : 0; const singularRate = data.lootItems ? Math.round(data.singulars / data.lootItems * 100) : 0; return <section key={tier}><header><b>T{tier}</b><span>{data.attempts} attempt{data.attempts === 1 ? '' : 's'}</span></header><div><span>EXTRACT <b>{extractRate}%</b></span><span>DEEP CHOICE <b>{deepChoice}%</b></span><span>AVG DMG <b>{avgDamage}</b></span><span>AVG TIME <b>{avgDuration}s</b></span><span>TTK PROXY <b>{killInterval.toFixed(1)}s</b></span><span>AVG RQ <b>{avgRq.toFixed(2)}</b></span><span>SINGULAR <b>{singularRate}%</b></span></div><small>GRADES // {Object.entries(data.modifierGrades).map(([grade, count]) => `G${grade}:${count}`).join(' · ')}</small></section>; })}</div>{protocolCombos.length > 0 && <div className="protocol-audit"><b>COMMON ELITE PROTOCOL PACKAGES</b>{protocolCombos.map(([combo, count]) => <span key={combo}>{combo} // {count}</span>)}</div>}</div>;
}
