from pathlib import Path
import json
import re

root = Path('.')

def read(path):
    return (root / path).read_text()

def write(path, text):
    (root / path).write_text(text)

def remove_file(path):
    p = root / path
    if p.exists():
        p.unlink()

# Retired Three-only implementation files proven unused by the executable audit.
for path in [
    'src/game/threeCombatRenderer.ts',
    'src/game/webGpuRefineryRenderer.ts',
    'src/game/hardSciFiVisuals.ts',
    'src/game/mapVisuals.ts',
    'src/game/refineryBloom.ts',
    'src/game/refineryIbl.ts',
    'scripts/measure-webgpu-delivery-cost.mjs',
]:
    remove_file(path)

# Reduce graphicsAssets.ts to the engine-neutral authored-asset contract.
write('src/game/graphicsAssets.ts', r'''export type GraphicsAssetClass = 'operator' | 'enemy' | 'boss' | 'weapon' | 'environment-module' | 'pickup' | 'interactable';
export type GraphicsAssetLod = 0 | 1 | 2;

export type GraphicsAssetSpec = {
  id: string;
  assetClass: GraphicsAssetClass;
  url: string;
  lod: GraphicsAssetLod;
  triangleBudget: number;
  compressedByteBudget: number;
};

export type GraphicsAssetFamily = {
  id: string;
  lods: Partial<Record<GraphicsAssetLod, GraphicsAssetSpec>>;
};

export type GraphicsAssetRuntimeBudget = {
  maxCachedCompressedBytes: number;
  maxTextureAnisotropy: 1 | 2 | 4;
};

export const GRAPHICS_ASSET_STANDARDS = {
  runtimeFormat: 'glb',
  unitScaleMeters: 1,
  upAxis: '+Y',
  forwardAxis: '+X',
  modelRoot: '/assets/models/',
  compression: {
    mesh: 'meshopt',
    texture: 'ktx2',
    ktx2WorkerLimit: 2,
  },
  maxTextureDimension: {
    operator: 2048,
    enemy: 1024,
    boss: 2048,
    weapon: 1024,
    'environment-module': 1024,
    pickup: 512,
    interactable: 1024,
  },
  defaultBudgets: {
    operator: { triangles: 45_000, compressedBytes: 2_500_000 },
    enemy: { triangles: 30_000, compressedBytes: 1_500_000 },
    boss: { triangles: 60_000, compressedBytes: 3_500_000 },
    weapon: { triangles: 12_000, compressedBytes: 800_000 },
    'environment-module': { triangles: 20_000, compressedBytes: 1_200_000 },
    pickup: { triangles: 4_000, compressedBytes: 240_000 },
    interactable: { triangles: 8_000, compressedBytes: 480_000 },
  },
} as const;

export function createGraphicsAssetSpec(
  id: string,
  assetClass: GraphicsAssetClass,
  url: string,
  lod: GraphicsAssetLod = 0,
): GraphicsAssetSpec {
  const budget = GRAPHICS_ASSET_STANDARDS.defaultBudgets[assetClass];
  return {
    id,
    assetClass,
    url,
    lod,
    triangleBudget: budget.triangles,
    compressedByteBudget: budget.compressedBytes,
  };
}

export function validateGraphicsAssetSpec(spec: GraphicsAssetSpec) {
  const issues: string[] = [];
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(spec.id)) issues.push('id must use lowercase kebab-case');
  if (!spec.url.startsWith(GRAPHICS_ASSET_STANDARDS.modelRoot)) issues.push(`url must live under ${GRAPHICS_ASSET_STANDARDS.modelRoot}`);
  if (!spec.url.toLowerCase().endsWith('.glb')) issues.push('runtime asset must be a .glb file');
  if (!spec.url.toLowerCase().endsWith(`-lod${spec.lod}.glb`)) issues.push(`url filename must end in -lod${spec.lod}.glb`);
  if (!Number.isFinite(spec.triangleBudget) || spec.triangleBudget <= 0) issues.push('triangleBudget must be positive');
  if (!Number.isFinite(spec.compressedByteBudget) || spec.compressedByteBudget <= 0) issues.push('compressedByteBudget must be positive');
  return issues;
}

export function graphicsAssetLodForDetailScale(detailScale: number): GraphicsAssetLod {
  if (!Number.isFinite(detailScale)) return 2;
  if (detailScale >= 0.9) return 0;
  if (detailScale >= 0.62) return 1;
  return 2;
}

export function selectGraphicsAssetSpec(family: GraphicsAssetFamily, detailScale: number): GraphicsAssetSpec | null {
  const preferred = graphicsAssetLodForDetailScale(detailScale);
  const order: Record<GraphicsAssetLod, GraphicsAssetLod[]> = {
    0: [0, 1, 2],
    1: [1, 2, 0],
    2: [2, 1, 0],
  };
  for (const lod of order[preferred]) {
    const spec = family.lods[lod];
    if (spec) return spec;
  }
  return null;
}
''')

# Remove Three package dependencies. package-lock is regenerated by CI after this script.
pkg = json.loads(read('package.json'))
pkg.get('dependencies', {}).pop('three', None)
pkg.get('devDependencies', {}).pop('@types/three', None)
write('package.json', json.dumps(pkg, indent=2) + '\n')

# Babylon-only codec preparation; purge the retired generated Three Basis directory.
write('scripts/prepare-graphics-codecs.mjs', r'''import { copyFile, mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = process.cwd();
const babylonPackage = JSON.parse(await readFile(resolve(root, 'node_modules/@babylonjs/core/package.json'), 'utf8'));
const babylonKtx2Package = JSON.parse(await readFile(resolve(root, 'node_modules/babylonjs-ktx2decoder/package.json'), 'utf8'));
const meshoptimizerPackage = JSON.parse(await readFile(resolve(root, 'node_modules/meshoptimizer/package.json'), 'utf8'));

async function copyRuntimeFile(source, target) {
  await copyFile(source, target);
  const info = await stat(target);
  if (!info.isFile() || info.size <= 0) throw new Error(`graphics codec copy failed: ${target}`);
  return info.size;
}

await rm(resolve(root, 'public/assets/codecs/basis'), { recursive: true, force: true });

const babylonTargetDir = resolve(root, 'public/assets/codecs/babylon');
await rm(babylonTargetDir, { recursive: true, force: true });
await mkdir(babylonTargetDir, { recursive: true });
const babylonSources = [
  ['node_modules/@babylonjs/core/Materials/Textures/Loaders/babylon.ktx2Decoder.js', 'babylon.ktx2Decoder.js'],
  ['node_modules/meshoptimizer/meshopt_decoder.js', 'meshopt_decoder.js'],
  ['node_modules/babylonjs-ktx2decoder/msc_basis_transcoder.js', 'msc_basis_transcoder.js'],
  ['node_modules/babylonjs-ktx2decoder/msc_basis_transcoder.wasm', 'msc_basis_transcoder.wasm'],
  ['node_modules/babylonjs-ktx2decoder/uastc_astc.wasm', 'uastc_astc.wasm'],
  ['node_modules/babylonjs-ktx2decoder/uastc_bc7.wasm', 'uastc_bc7.wasm'],
  ['node_modules/babylonjs-ktx2decoder/uastc_r8_unorm.wasm', 'uastc_r8_unorm.wasm'],
  ['node_modules/babylonjs-ktx2decoder/uastc_rg8_unorm.wasm', 'uastc_rg8_unorm.wasm'],
  ['node_modules/babylonjs-ktx2decoder/uastc_rgba8_srgb_v2.wasm', 'uastc_rgba8_srgb_v2.wasm'],
  ['node_modules/babylonjs-ktx2decoder/uastc_rgba8_unorm_v2.wasm', 'uastc_rgba8_unorm_v2.wasm'],
  ['node_modules/babylonjs-ktx2decoder/zstddec.wasm', 'zstddec.wasm'],
];
let babylonTotalBytes = 0;
for (const [source, filename] of babylonSources) {
  babylonTotalBytes += await copyRuntimeFile(resolve(root, source), resolve(babylonTargetDir, filename));
}
await writeFile(resolve(babylonTargetDir, 'manifest.json'), JSON.stringify({
  codec: 'babylon-glb-ktx2-meshopt',
  babylonVersion: babylonPackage.version,
  ktx2DecoderVersion: babylonKtx2Package.version,
  meshoptimizerVersion: meshoptimizerPackage.version,
  files: babylonSources.map(([, filename]) => filename),
  totalBytes: babylonTotalBytes,
}, null, 2));

console.log(`GRAPHICS_CODECS_READY babylon=${babylonPackage.version} meshopt=${meshoptimizerPackage.version} files=${babylonSources.length} bytes=${babylonTotalBytes}`);
''')

# Remove Three-specific manual chunks from Vite.
vite = read('vite.config.ts')
vite = vite.replace("          if (normalizedId.endsWith('/node_modules/three/build/three.core.js')) return 'three-core';\n", '')
vite = vite.replace("          if (normalizedId.endsWith('/node_modules/three/build/three.module.js')) return 'three-webgl';\n", '')
write('vite.config.ts', vite)

# Replace old bundle expectations with a strict absence guard.
bundle = read('tests/client-bundle-architecture.mjs')
bundle = re.sub(
    r"const threeChunks = jsFiles\.filter\(name => name\.startsWith\('three-core-'\) \|\| name\.startsWith\('three-webgl-'\)\);\nassert\(threeChunks\.some\(name => name\.startsWith\('three-core-'\)\), 'Three\.js core is not isolated in its deferred chunk\.'\);\nassert\(threeChunks\.some\(name => name\.startsWith\('three-webgl-'\)\), 'Three\.js WebGL renderer is not isolated in its deferred chunk\.'\);\n",
    "const threeChunks = jsFiles.filter(name => name.startsWith('three-') || name.startsWith('three.') || name.startsWith('webGpuRefineryRenderer-'));\nassert(threeChunks.length === 0, `Three runtime chunks must not ship after P27-D9: ${threeChunks.join(',')}`);\n",
    bundle,
)
write('tests/client-bundle-architecture.mjs', bundle)

# Runtime codec test is now Babylon-only and explicitly rejects the retired Basis directory.
runtime_assets = read('tests/graphics-runtime-assets.mjs')
start = runtime_assets.find("const threeCodecRoot =")
end = runtime_assets.find("const babylonCodecRoot =")
if start >= 0 and end > start:
    runtime_assets = runtime_assets[:start] + "const retiredThreeCodecRoot = resolve(process.cwd(), 'dist/assets/codecs/basis');\ntry {\n  await stat(retiredThreeCodecRoot);\n  throw new Error('retired Three Basis codec directory must not ship');\n} catch (error) {\n  if (error?.code !== 'ENOENT') throw error;\n}\n\n" + runtime_assets[end:]
runtime_assets = re.sub(r"console\.log\(\n\s*`GRAPHICS_RUNTIME_ASSETS_PASS threeFiles=2 threeBytes=\$\{threeTotalBytes\} three=\$\{threeManifest\.threeVersion\} babylonFiles=\$\{babylonFiles\.length\} babylonBytes=\$\{babylonTotalBytes\} babylon=\$\{babylonManifest\.babylonVersion\} meshopt=\$\{babylonManifest\.meshoptimizerVersion\}`,\n\);", "console.log(`GRAPHICS_RUNTIME_ASSETS_PASS threeFiles=0 babylonFiles=${babylonFiles.length} babylonBytes=${babylonTotalBytes} babylon=${babylonManifest.babylonVersion} meshopt=${babylonManifest.meshoptimizerVersion}`);", runtime_assets)
write('tests/graphics-runtime-assets.mjs', runtime_assets)

# Renderer-neutral bloom profile owns these helpers now.
for path in ['tests/refinery-bloom.ts']:
    text = read(path).replace("../src/game/refineryBloom'", "../src/game/refineryBloomProfile'")
    write(path, text)

# Renderer-neutral lighting profile owns the IBL profile now.
text = read('tests/world-material-polish.ts').replace("../src/game/refineryIbl'", "../src/game/refineryLightingProfile'")
write('tests/world-material-polish.ts', text)

print('P27_D9_MIGRATION_APPLIED')
